/**
 * SciStudio public-API completion + hover for the in-app Monaco editor (#1875).
 *
 * Monaco's built-in Python support only offers *word-based* suggestions — words
 * that already appear in the current file — and has no knowledge of the
 * SciStudio authoring API. This module feeds Monaco a data-driven completion and
 * hover provider built from ``apiManifest.generated.json``, which is generated by
 * ``scripts/docs/build_reference.py`` from the same ``__all__`` + stability +
 * docstring introspection as the human API reference. The manifest is generated,
 * never hand-edited, so the editor can never drift from the public surface.
 *
 * Scope (Plan A, #1875): suggest the importable public symbols (signatures,
 * one-line summaries, stability shown as completion detail / hover), complete the
 * names inside a ``from <root> import ...`` clause, and offer a Block scaffold
 * snippet. Real type-aware member completion (``df.<methods>``) is intentionally
 * out of scope — it needs a Python language service (a tracked follow-up).
 */

import manifest from "./apiManifest.generated.json";

export interface ApiMember {
  name: string;
  kind: string;
  signature: string;
  summary: string;
}

export interface ApiSymbol {
  name: string;
  module: string;
  kind: string;
  signature: string;
  summary: string;
  stability: string | null;
  since: string | null;
  members?: ApiMember[];
}

interface ApiManifest {
  version: string;
  roots: { module: string; symbols: ApiSymbol[] }[];
}

export interface ApiCompletionSpec {
  label: string;
  insertText: string;
  detail: string;
  documentation: string;
  /** Logical kind; mapped to a Monaco ``CompletionItemKind`` at registration. */
  kind: string;
  /** When true the ``insertText`` is a Monaco snippet (tab stops). */
  snippet?: boolean;
}

const MANIFEST = manifest as unknown as ApiManifest;

/** The canonical import roots, in manifest (declaration) order. */
export const CANONICAL_ROOTS: string[] = MANIFEST.roots.map((r) => r.module);

/** Every public symbol across all roots, deduplicated by ``module + name``. */
export const ALL_SYMBOLS: ApiSymbol[] = MANIFEST.roots.flatMap((r) => r.symbols);

const SYMBOLS_BY_ROOT = new Map<string, ApiSymbol[]>(
  MANIFEST.roots.map((r) => [r.module, r.symbols]),
);

/** First public symbol with a given name (for hover lookup by bare name). */
const SYMBOL_BY_NAME = new Map<string, ApiSymbol>();
for (const sym of ALL_SYMBOLS) {
  if (!SYMBOL_BY_NAME.has(sym.name)) SYMBOL_BY_NAME.set(sym.name, sym);
}

/**
 * A Block subclass scaffold, mirroring the new-custom-block starter template.
 * Surfaced by typing ``sci`` so it does not collide with the ``Block`` symbol.
 */
const SCAFFOLD_SPECS: ApiCompletionSpec[] = [
  {
    label: "sci-block",
    kind: "snippet",
    detail: "SciStudio · new Block scaffold",
    documentation: "Insert a minimal SciStudio `Block` subclass (ports + run()).",
    snippet: true,
    insertText: [
      "class ${1:MyBlock}(Block):",
      '    name: ClassVar[str] = "${2:My Block}"',
      '    description: ClassVar[str] = "${3:Describe what this block does.}"',
      "",
      "    input_ports: ClassVar[list[InputPort]] = [",
      '        InputPort(name="input", accepted_types=[${4:Array}], description="Input data"),',
      "    ]",
      "    output_ports: ClassVar[list[OutputPort]] = [",
      '        OutputPort(name="output", accepted_types=[${5:Array}], description="Output data"),',
      "    ]",
      "",
      "    def run(self, inputs: dict[str, Collection], config: BlockConfig)" +
        " -> dict[str, Collection]:",
      "        ${0:...}",
    ].join("\n"),
  },
];

/** The character immediately before the word being typed, or "" at line start. */
export function charBeforeWord(linePrefix: string): string {
  const beforeWord = linePrefix.replace(/[A-Za-z0-9_]*$/, "");
  return beforeWord.slice(-1);
}

/**
 * If ``linePrefix`` is inside a ``from <root> import ...`` clause whose root is a
 * known canonical root, return that root; otherwise ``null``.
 */
export function detectImportRoot(linePrefix: string): string | null {
  const match = /\bfrom\s+(scistudio[A-Za-z0-9_.]*)\s+import\b/.exec(linePrefix);
  if (!match) return null;
  const root = match[1];
  return SYMBOLS_BY_ROOT.has(root) ? root : null;
}

function renderDoc(sym: ApiSymbol): string {
  const parts: string[] = ["```python\n" + sym.name + sym.signature + "\n```"];
  const meta = [
    `from \`${sym.module}\``,
    sym.stability ? `**${sym.stability}**${sym.since ? ` · since ${sym.since}` : ""}` : "",
  ]
    .filter(Boolean)
    .join(" · ");
  if (meta) parts.push(meta);
  if (sym.summary) parts.push(sym.summary);
  if (sym.members && sym.members.length > 0) {
    parts.push("**Members**");
    parts.push(
      sym.members
        .map((m) => `- \`${m.name}${m.signature}\`${m.summary ? ` — ${m.summary}` : ""}`)
        .join("\n"),
    );
  }
  return parts.join("\n\n");
}

function toSpec(sym: ApiSymbol): ApiCompletionSpec {
  return {
    label: sym.name,
    insertText: sym.name,
    detail: `${sym.module}${sym.stability ? ` · ${sym.stability}` : ""}`,
    documentation: renderDoc(sym),
    kind: sym.kind,
  };
}

/**
 * Compute SciStudio-API completion specs for a cursor whose current line text up
 * to the cursor is ``linePrefix``. Pure (no Monaco) so it is unit-testable.
 */
export function suggestApiSymbols(args: { linePrefix: string }): ApiCompletionSpec[] {
  const { linePrefix } = args;
  // Member access (``foo.``) needs real type info — out of scope for Plan A.
  if (charBeforeWord(linePrefix) === ".") return [];

  const importRoot = detectImportRoot(linePrefix);
  if (importRoot !== null) {
    return (SYMBOLS_BY_ROOT.get(importRoot) ?? []).map(toSpec);
  }

  // General code context: every public symbol, plus the scaffold snippets.
  // Monaco filters this list by the typed prefix, so the user only sees matches.
  return [...SCAFFOLD_SPECS, ...ALL_SYMBOLS.map(toSpec)];
}

/** Hover markdown for a bare symbol name, or ``null`` when it is not public API. */
export function hoverMarkdownFor(word: string): string | null {
  const sym = SYMBOL_BY_NAME.get(word);
  return sym ? renderDoc(sym) : null;
}

// --------------------------------------------------------------------------
// Monaco wiring (kept thin; the logic above is the tested surface).
// --------------------------------------------------------------------------

interface MonacoPosition {
  lineNumber: number;
  column: number;
}

interface MonacoWordRange {
  startColumn: number;
  endColumn: number;
  word?: string;
}

interface MonacoModel {
  getLineContent?: (lineNumber: number) => string;
  getWordUntilPosition?: (position: MonacoPosition) => MonacoWordRange;
  getWordAtPosition?: (position: MonacoPosition) => MonacoWordRange | null;
}

interface MonacoRange {
  startLineNumber: number;
  startColumn: number;
  endLineNumber: number;
  endColumn: number;
}

interface MonacoCompletionItem {
  label: string;
  kind: number;
  insertText: string;
  insertTextRules?: number;
  detail: string;
  documentation: { value: string };
  range?: MonacoRange;
}

interface MonacoCompletionProvider {
  triggerCharacters?: string[];
  provideCompletionItems: (
    model: MonacoModel,
    position: MonacoPosition,
  ) => { suggestions: MonacoCompletionItem[] };
}

interface MonacoHoverProvider {
  provideHover: (
    model: MonacoModel,
    position: MonacoPosition,
  ) => { contents: { value: string }[]; range?: MonacoRange } | null;
}

interface MonacoLanguages {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  CompletionItemKind?: Record<string, any>;
  CompletionItemInsertTextRule?: { InsertAsSnippet?: number };
  registerCompletionItemProvider?: (
    language: string,
    provider: MonacoCompletionProvider,
  ) => { dispose: () => void };
  registerHoverProvider?: (
    language: string,
    provider: MonacoHoverProvider,
  ) => { dispose: () => void };
}

interface MonacoNamespace {
  languages?: MonacoLanguages;
  __scistudioApiCompletionsRegistered?: boolean;
}

/** Map a manifest/logical kind to a Monaco ``CompletionItemKind`` value. */
function monacoKind(monaco: MonacoNamespace, kind: string): number {
  const kinds = monaco.languages?.CompletionItemKind ?? {};
  const pick = (name: string): number | undefined =>
    typeof kinds[name] === "number" ? (kinds[name] as number) : undefined;
  switch (kind) {
    case "class":
    case "protocol":
    case "exception":
      return pick("Class") ?? 5;
    case "enum":
      return pick("Enum") ?? 15;
    case "function":
      return pick("Function") ?? 1;
    case "method":
      return pick("Method") ?? 0;
    case "property":
      return pick("Property") ?? 9;
    case "constant":
      return pick("Constant") ?? 14;
    case "type-alias":
      return pick("Variable") ?? 4;
    case "snippet":
      return pick("Snippet") ?? 27;
    default:
      return pick("Variable") ?? 4;
  }
}

function completionRange(model: MonacoModel, position: MonacoPosition): MonacoRange | undefined {
  const word = model.getWordUntilPosition?.(position);
  if (!word) return undefined;
  return {
    startLineNumber: position.lineNumber,
    startColumn: word.startColumn,
    endLineNumber: position.lineNumber,
    endColumn: word.endColumn,
  };
}

function linePrefixOf(model: MonacoModel, position: MonacoPosition): string {
  const line = model.getLineContent?.(position.lineNumber) ?? "";
  return line.slice(0, Math.max(0, position.column - 1));
}

export function registerApiCompletions(monaco: MonacoNamespace): void {
  if (monaco.__scistudioApiCompletionsRegistered) return;
  const languages = monaco.languages;
  if (!languages) return;

  const snippetRule = languages.CompletionItemInsertTextRule?.InsertAsSnippet;

  languages.registerCompletionItemProvider?.("python", {
    provideCompletionItems(model, position) {
      const linePrefix = linePrefixOf(model, position);
      const range = completionRange(model, position);
      const suggestions = suggestApiSymbols({ linePrefix }).map((spec) => ({
        label: spec.label,
        kind: monacoKind(monaco, spec.kind),
        insertText: spec.insertText,
        insertTextRules: spec.snippet ? snippetRule : undefined,
        detail: spec.detail,
        documentation: { value: spec.documentation },
        range,
      }));
      return { suggestions };
    },
  });

  languages.registerHoverProvider?.("python", {
    provideHover(model, position) {
      const word = model.getWordAtPosition?.(position);
      if (!word || !word.word) return null;
      const value = hoverMarkdownFor(word.word);
      if (value === null) return null;
      return {
        contents: [{ value }],
        range: {
          startLineNumber: position.lineNumber,
          startColumn: word.startColumn,
          endLineNumber: position.lineNumber,
          endColumn: word.endColumn,
        },
      };
    },
  });

  monaco.__scistudioApiCompletionsRegistered = true;
}
