"""Generated by SciStudio from the exploration notebook find_peaks.ipynb.

Packaged at notebook commit 4f2a1c9 (ADR-054 FR-037, FR-041). Edit the
notebook beside this file and package again rather than editing this
declaration: packaging replaces both files in place.
"""

from __future__ import annotations

from typing import ClassVar

from scistudio.blocks.base.interactive import InteractionPolicy
from scistudio.blocks.base.ports import InputPort, OutputPort
from scistudio.core.types.dataframe import DataFrame
from scistudio.explore.packaging import PackagedNotebookBlock


class FindPeaks(PackagedNotebookBlock):
    """Find Peaks, packaged from an exploration notebook."""

    name: ClassVar[str] = "Find Peaks"
    description: ClassVar[str] = "Packaged from the exploration notebook find_peaks.ipynb."
    version: ClassVar[str] = "4f2a1c9"

    notebook_filename: ClassVar[str] = "find_peaks.ipynb"
    notebook_commit: ClassVar[str] = "4f2a1c9"
    blocks_dirname: ClassVar[str] = "blocks"
    slice_cells: ClassVar[tuple[str, ...]] = ("c1", "c2", "c3", "c4", "c5")
    packaged_inputs: ClassVar[tuple[dict[str, str], ...]] = (
        {"name": "readings", "data_type": "DataFrame", "extension": ".parquet"},
    )
    packaged_outputs: ClassVar[tuple[dict[str, str], ...]] = (
        {"name": "peaks", "data_type": "DataFrame", "extension": ".parquet"},
    )
    on_new_input: ClassVar[InteractionPolicy | str] = "replay"

    variadic_inputs: ClassVar[bool] = False
    variadic_outputs: ClassVar[bool] = False
    input_ports: ClassVar[list[InputPort]] = [
        InputPort(
            name="readings",
            accepted_types=[DataFrame],
            description="Declared in the notebook as readings.",
        )
    ]
    output_ports: ClassVar[list[OutputPort]] = [
        OutputPort(
            name="peaks",
            accepted_types=[DataFrame],
            description="Declared in the notebook as peaks (peaks).",
        )
    ]
