"""Auto-generate ``docs/adr/_consolidated/cascade-current.md`` (ADR-042 §27.5).

Walks every addendum ADR's ``amends:`` frontmatter and applies its
amendments to the base ADR text per the AmendmentKind precedence rules:

* ``extend`` — append a "(See also ADR-NNN-X §Y)" note after the target
  section.
* ``replace`` — substitute the addendum's body for the target section's
  body.
* ``constrain`` — append the addendum's text after the target with an
  "Additional restriction" header.
* ``clarify`` — append a "Clarification per ADR-NNN-X §Y" footnote.

The output is a single Markdown file written to
``docs/adr/_consolidated/cascade-current.md`` (marked auto-generated by
a leading frontmatter block).

Invocation::

    python scripts/audit/consolidate_cascade.py --repo-root .

References
----------
ADR-042 §27.5 — generation: AUTO; hand-edits rejected.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

_THIS_FILE = Path(__file__).resolve()
_REPO_ROOT = _THIS_FILE.parent.parent.parent
_SRC_DIR = _REPO_ROOT / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(prog="consolidate_cascade")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="repository root (default: cwd)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=("Output path (default: <repo-root>/docs/adr/_consolidated/cascade-current.md)"),
    )
    parser.add_argument(
        "--base",
        type=int,
        default=42,
        help="ADR number to use as the consolidation base (default: 42)",
    )
    args = parser.parse_args(argv)

    output = args.output or args.repo_root / "docs" / "adr" / "_consolidated" / "cascade-current.md"
    md = consolidate(args.repo_root, base_adr=args.base)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(md, encoding="utf-8")
    print(f"wrote consolidated cascade to {output}")
    return 0


# ---------------------------------------------------------------------------
# Library API
# ---------------------------------------------------------------------------


def consolidate(repo_root: Path, *, base_adr: int = 42) -> str:
    """Return the consolidated Markdown for ``base_adr`` plus all its
    amending ADRs."""
    adr_dir = repo_root / "docs" / "adr"
    base_path = adr_dir / f"ADR-{base_adr:03d}.md"
    if not base_path.is_file():
        return _empty_consolidation(base_adr, reason=f"{base_path} not found")
    base_text = base_path.read_text(encoding="utf-8")
    base_prose = _strip_frontmatter(base_text)

    # Collect addenda + their amendments aimed at base_adr.
    amendments_by_section: dict[str, list[tuple[int, dict[str, Any]]]] = defaultdict(list)
    for path in sorted(adr_dir.glob("ADR-*.md")):
        if path.name == f"ADR-{base_adr:03d}.md":
            continue
        fm = _parse_frontmatter(path)
        if fm is None:
            continue
        try:
            adr_num = int(fm.get("adr"))
        except (TypeError, ValueError):
            continue
        amends_raw = fm.get("amends") or []
        for raw in amends_raw:
            if not isinstance(raw, dict):
                continue
            target = str(raw.get("target", ""))
            m = re.match(rf"^ADR-{base_adr:03d}\s+§(\d+(?:\.\d+)*)", target)
            if not m:
                continue
            section = m.group(1)
            amendments_by_section[section].append((adr_num, raw))

    # Apply each section's amendments by rewriting that section.
    result_lines = list(base_prose.splitlines())
    for section, amends in amendments_by_section.items():
        result_lines = _apply_section_amendments(result_lines, section, amends)

    return _wrap_with_header(base_adr, "\n".join(result_lines))


# ---------------------------------------------------------------------------
# Section-level rewriting
# ---------------------------------------------------------------------------


def _apply_section_amendments(lines: list[str], section: str, amends: list[tuple[int, dict[str, Any]]]) -> list[str]:
    """Return ``lines`` with all amendments for ``section`` applied."""
    start, end = _find_section_bounds(lines, section)
    if start is None:
        return lines

    section_lines = lines[start : end if end is not None else len(lines)]
    extras: list[str] = []
    replaced = False

    for adr_num, raw in amends:
        kind = str(raw.get("kind", "")).lower()
        summary = str(raw.get("summary", ""))
        ref = f"ADR-{adr_num:03d}"
        if kind == "replace" and not replaced:
            # Wipe section body (keep heading line) and inline summary.
            heading = section_lines[0]
            section_lines = [
                heading,
                "",
                f"> Replaced by {ref}: {summary}",
                "",
            ]
            replaced = True
        elif kind == "replace" and replaced:
            extras.append(f"\n> NOTE: {ref} also declares a 'replace' on this section; conflict.\n")
        elif kind == "extend":
            extras.append(f"\n> See also: {ref} extends this section — {summary}\n")
        elif kind == "constrain":
            extras.append(f"\n#### Additional restriction (per {ref})\n\n{summary}\n")
        elif kind == "clarify":
            extras.append(f"\n> Clarification per {ref}: {summary}\n")
    if extras:
        section_lines.extend(extras)

    return lines[:start] + section_lines + (lines[end:] if end is not None else [])


def _find_section_bounds(lines: list[str], section: str) -> tuple[int | None, int | None]:
    """Return ``(start_idx, end_idx)`` of the requested section.

    ``end_idx`` is one past the last line in the section (exclusive),
    or ``None`` when the section runs to EOF. ``start_idx`` is the
    index of the heading line itself.
    """
    start: int | None = None
    start_level: int | None = None
    for i, line in enumerate(lines):
        m = re.match(r"^(#{1,6})\s+(\d+(?:\.\d+)*)", line)
        if not m:
            continue
        if m.group(2) == section:
            start = i
            start_level = len(m.group(1))
            break
    if start is None:
        return None, None
    # Walk forward until we hit a heading at <= start_level depth.
    for j in range(start + 1, len(lines)):
        m = re.match(r"^(#{1,6})\s+", lines[j])
        if m and len(m.group(1)) <= (start_level or 1):
            return start, j
    return start, None


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------


def _parse_frontmatter(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    block = text[3:end]
    try:
        data = yaml.safe_load(block)
    except yaml.YAMLError:
        return None
    return data if isinstance(data, dict) else None


def _strip_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    if end == -1:
        return text
    return text[end + 4 :]


def _wrap_with_header(base_adr: int, body: str) -> str:
    now = datetime.now(UTC).isoformat(timespec="seconds")
    return (
        "<!--\n"
        f"AUTO-GENERATED by scripts/audit/consolidate_cascade.py at {now}.\n"
        f"Base: ADR-{base_adr:03d}. DO NOT EDIT BY HAND.\n"
        "Per ADR-042 §27.5: generation is AUTO; hand-edits are rejected.\n"
        "-->\n\n"
        f"# ADR-{base_adr:03d} consolidated cascade view\n\n"
        f"{body}\n"
    )


def _empty_consolidation(base_adr: int, *, reason: str) -> str:
    return f"<!--\nconsolidate_cascade.py: no consolidation produced for ADR-{base_adr:03d}.\nreason: {reason}\n-->\n"


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
