#!/usr/bin/env python3
"""Generate the SciStudio public API reference (ADR-052 §7, spec §16 step 2).

The author-facing API reference is **generated from docstrings + the
``scistudio.stability`` decorators** so it cannot drift from the code and the
tier / ``Since`` badges render automatically rather than from a hand-maintained
table (ADR-052 §7).

What this script does:

1. Imports the **thirteen canonical public roots** (ADR-052 §3/§4; the SciStudio
   freeze contract) and, for each, reads its declared ``__all__`` — the public
   surface. Symbols outside ``__all__`` (and ``internal``-tier class members) are
   excluded even if they have docstrings.
2. For every public symbol it reads the stability tier and ``Since`` through the
   single read path :func:`scistudio.stability.get_stability` and renders a
   badge next to the entry. It reads deprecation through
   :func:`scistudio.stability.get_deprecation`, on the symbol first and on its
   canonical root module second (a module-wide deprecation also covers constants
   and type aliases that cannot carry a marker), and renders a deprecation notice
   on the root page, on each deprecated symbol, and in the index (#2426).
3. Emits one Markdown page per root under ``docs/user/reference/`` plus a
   version-stamped ``index.md``. Each page contains an ``mkdocstrings``
   (``griffe``) autodoc directive per symbol, so ``mkdocstrings`` renders the
   docstring + signature while this script supplies the filter + badge.
4. Runs ``mkdocs build --strict`` (unless ``--generate-only``) so the reference
   provably builds green.

The generated pages under ``docs/user/reference/`` are a generated artifact
(ADR-042 generated-doc rule): regenerate with this script, do not hand-edit.

Run (never ``pip install -e .``)::

    PYTHONPATH=$PWD/src python scripts/docs/build_reference.py
    PYTHONPATH=$PWD/src python scripts/docs/build_reference.py --generate-only

``mike`` multi-version hosting is deferred (single-version stamp for alpha):

    TODO(#1817): multi-version published reference docs (mike) once >1 core line
      is supported. Out of scope per ADR-052 §7 (single-version generated docs
      for alpha). Followup: https://github.com/jiazhenz026/SciStudio/issues/1817
"""

from __future__ import annotations

import argparse
import enum
import importlib
import inspect
import re
import subprocess
import sys
import types
from collections.abc import Callable
from pathlib import Path
from typing import Any, cast

#: Convert in-docstring Sphinx cross-reference roles (``:meth:`run```,
#: ``:class:`pandas.DataFrame```) into plain inline code for the self-contained
#: Markdown reference (the mkdocs site does the same via griffe_sphinx_roles.py).
_SPHINX_ROLE_RE = re.compile(r":[a-zA-Z]+:`~?([^`]+)`")


def _strip_sphinx_roles(text: str) -> str:
    return _SPHINX_ROLE_RE.sub(r"`\1`", text)


REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from scistudio.stability import DeprecationInfo, get_deprecation, get_stability  # noqa: E402

#: The thirteen canonical public roots. Public surface = each root's ``__all__``
#: (ADR-052 §3/§4; identical to the SciStudio freeze contract). ``api.app`` and
#: ``api.seam`` are the ADR-055 identity seam an edition composes on (#2304);
#: ``panels`` is the ADR-054 panels surface (#2426). The two ``previewers`` roots
#: are deprecated as a whole and removed in 0.3.6 (ADR-054 §8, #2288).
CANONICAL_ROOTS: tuple[str, ...] = (
    "scistudio.core.types",
    "scistudio.core.meta",
    "scistudio.blocks.base",
    "scistudio.blocks.process",
    "scistudio.blocks.io",
    "scistudio.blocks.app",
    "scistudio.blocks.code",
    "scistudio.previewers.models",
    "scistudio.previewers.data_access",
    "scistudio.tutorials",
    "scistudio.api.app",
    "scistudio.api.seam",
    "scistudio.panels",
)

REFERENCE_DIR = REPO_ROOT / "docs" / "user" / "reference"
#: Self-contained reference (ADR-052 §7; #1850). Unlike ``REFERENCE_DIR`` (which
#: holds ``mkdocstrings`` directive shells that only render under an mkdocs
#: build), this directory holds **self-contained** Markdown with real signatures
#: and docstrings inlined, so it is readable as-is. It lives inside the package
#: so it ships in the wheel and is provisioned into ``<project>/user-guide/
#: api-reference/`` for the in-project human + embedded agent.
PACKAGE_REFERENCE_DIR = SRC / "scistudio" / "_user_guide" / "api-reference"
SITE_DIR = REPO_ROOT / "build" / "mkdocs-site"  # gitignored (build/)
MKDOCS_CONFIG = REPO_ROOT / "mkdocs.yml"

_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/docs/build_reference.py. "
    "Do not hand-edit; regenerate from docstrings + stability decorators. -->\n"
)


def _core_version() -> str:
    """Best-effort core version string for the single-version stamp (ADR-052 §7)."""
    try:
        import scistudio

        version = getattr(scistudio, "__version__", None)
        if version:
            return str(version)
    except Exception:  # pragma: no cover - defensive
        pass
    try:
        from scistudio._version import BASE_VERSION, CHANNEL

        return f"{BASE_VERSION} ({CHANNEL})"
    except Exception:  # pragma: no cover - defensive
        return "unknown"


def _workflow_reference() -> Any:
    """The workflow YAML file format generator, which lives beside this script."""
    here = str(Path(__file__).resolve().parent)
    if here not in sys.path:
        sys.path.insert(0, here)
    return importlib.import_module("build_workflow_reference")


def _symbol_kind(obj: object) -> str:
    """Classify a public symbol for its heading label."""
    if inspect.isclass(obj):
        if isinstance(obj, enum.EnumType):
            return "enum"
        if issubclass(obj, BaseException):
            return "exception"
        if getattr(obj, "_is_protocol", False):
            return "protocol"
        return "class"
    if inspect.isroutine(obj):
        return "function"
    if isinstance(obj, (types.GenericAlias, types.UnionType)) or "Alias" in type(obj).__name__:
        return "type-alias"
    return "constant"


def _deprecation_of(module: types.ModuleType, obj: object) -> DeprecationInfo | None:
    """Effective deprecation of a public symbol: its own marker, else its root's."""
    return get_deprecation(obj) or get_deprecation(module)


def _deprecation_sentence(info: DeprecationInfo) -> str:
    """One sentence stating when a deprecation started, when it ends, and what replaces it."""
    return (
        f"**Deprecated** since `{info.since}`; still supported until it is removed in "
        f"`{info.removed_in}`. Use instead: {info.replacement}"
    )


def _root_deprecation_sentence(info: DeprecationInfo) -> str:
    """The root-page banner: the whole public surface of the root is deprecated."""
    return (
        f"Every symbol on this page is deprecated since `{info.since}` and is removed in "
        f"`{info.removed_in}`; each keeps working until then. Use instead: {info.replacement}"
    )


def _badge(obj: object) -> str:
    """Render the tier / Since badge for a symbol from ``get_stability``.

    Reads the single source of truth. A symbol whose tier cannot be machine-read
    (a bare ``str`` constant or a ``list[...]`` / ``collections.abc.Callable``
    generic-alias has no writable ``__dict__``) renders as *unmarked*; its tier
    is recorded in the module source and the spec (ADR-052 §8.1).
    """
    info = get_stability(obj)
    if info is None:
        return "> _Stability: unmarked — no runtime stability marker is available for this constant or type alias._"
    since = f" · **Since:** `{info.since}`" if info.since else ""
    return f"> **Stability:** `{info.tier}`{since}"


def _internal_member_filters(cls: type) -> list[str]:
    """``mkdocstrings`` filters excluding non-underscore ``internal``-tier members.

    Class members are otherwise filtered only by the default ``!^_`` rule, so an
    ``internal``-tier method with a public-looking name (e.g.
    ``PreviewDataAccess.png_data_uri``) would leak into the reference; this
    excludes it (ADR-052 §7 — ``internal`` symbols are excluded).
    """
    filters: list[str] = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        info = get_stability(value)
        if info is not None and info.tier == "internal":
            filters.append(f'"!^{name}$"')
    return filters


def _directive(path: str, *, is_class: bool, extra_filters: list[str]) -> str:
    filters = ['"!^_"', *extra_filters]
    lines = [
        f"::: {path}",
        "    options:",
        "      show_root_heading: false",
        "      show_root_toc_entry: false",
        "      show_source: false",
        "      heading_level: 4",
        "      members_order: source",
        f"      filters: [{', '.join(filters)}]",
    ]
    if not is_class:
        lines.append("      show_labels: false")
    return "\n".join(lines)


def _render_root_page(root: str) -> tuple[str, int, int]:
    """Render one root's reference page. Returns (markdown, public_count, marked_count)."""
    module = importlib.import_module(root)
    public = sorted(getattr(module, "__all__", []))
    marked = 0

    body = [
        _GENERATED_BANNER,
        f"# `{root}`\n",
        f"Canonical import root: `from {root} import ...`\n",
    ]
    root_deprecation = get_deprecation(module)
    if root_deprecation is not None:
        body.append(f'!!! warning "Deprecated"\n    {_root_deprecation_sentence(root_deprecation)}\n')
    body.append(
        "Public surface — every symbol below is declared in this module's "
        f"`__all__` ({len(public)} symbols). Stability tier and `Since` are read "
        "from the `scistudio.stability` decorators.\n",
    )

    for name in public:
        obj = getattr(module, name)
        kind = _symbol_kind(obj)
        if get_stability(obj) is not None:
            marked += 1
        is_class = inspect.isclass(obj)
        extra_filters = _internal_member_filters(obj) if is_class else []
        deprecation = _deprecation_of(module, obj)
        suffix = " · deprecated" if deprecation is not None else ""
        body.append(f"## `{name}` — _{kind}_{suffix}\n")
        badge = _badge(obj)
        if deprecation is not None:
            badge += f"\n>\n> {_deprecation_sentence(deprecation)}"
        body.append(badge + "\n")
        body.append(_directive(f"{root}.{name}", is_class=is_class, extra_filters=extra_filters) + "\n")

    return "\n".join(body) + "\n", len(public), marked


def _root_is_deprecated(root: str) -> bool:
    return get_deprecation(importlib.import_module(root)) is not None


def _render_index(stats: list[tuple[str, int, int]]) -> str:
    version = _core_version()
    lines = [
        _GENERATED_BANNER,
        "# SciStudio API Reference\n",
        f"**Version:** `{version}` — reference for this release.\n",
        "This reference is **generated** from the public API's docstrings and "
        "the `scistudio.stability` decorators. It contains only the "
        "public surface — the symbols declared in each canonical root's "
        "`__all__`; `internal` symbols are excluded. Do not hand-edit; "
        "regenerate with `scripts/docs/build_reference.py`.\n",
        "## Stability tiers\n",
        "- **`stable`** — supported; no incompatible change within a major "
        "version without deprecation first.\n"
        "- **`provisional`** — usable but still settling; may change in a minor "
        "release with a changelog note.\n"
        "- **`internal`** — excluded from this reference (no promise).\n",
        "A symbol can also be **deprecated**. Deprecation does not change its "
        "tier: the symbol keeps working as documented until the release named "
        "in its notice removes it, and the notice names the replacement.\n",
        "A handful of public constants and type-aliases (a bare `str`, a "
        "`list[...]` or `collections.abc.Callable` alias) cannot carry a runtime "
        "stability marker and render as *unmarked*.\n",
        "## Canonical public roots\n",
    ]
    for root, public_count, marked in stats:
        page = f"{root}.md"
        note = " — **deprecated**" if _root_is_deprecated(root) else ""
        lines.append(f"- [`{root}`]({page}) — {public_count} public symbols ({marked} stability-marked){note}")
    lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Self-contained renderer (#1850): real signatures + docstrings inlined, so the
# reference is readable without an mkdocs build and can be provisioned as-is.
# --------------------------------------------------------------------------


def _sc_badge(obj: object) -> str:
    info = get_stability(obj)
    if info is None:
        return "_unmarked — no runtime stability marker_"
    since = f" · Since `{info.since}`" if info.since else ""
    return f"`{info.tier}`{since}"


def _sc_signature(obj: object) -> str | None:
    """Best-effort signature string; ``None`` when uninspectable."""
    try:
        # The public surface includes constants and type aliases, which are not
        # callable at all. ``inspect.signature`` raises TypeError for those and
        # the caller renders the symbol without a signature, so the cast states
        # what the ``except`` already handles.
        return str(inspect.signature(cast("Callable[..., Any]", obj)))
    except (TypeError, ValueError):
        return None


def _sc_firstline(doc: str | None) -> str:
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        if line.strip():
            return _strip_sphinx_roles(line.strip())
    return ""


def _sc_public_members(cls: type) -> list[tuple[str, object]]:
    """Public, non-``internal`` members defined on ``cls`` itself (not inherited)."""
    members: list[tuple[str, object]] = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        info = get_stability(value)
        if info is not None and info.tier == "internal":
            continue
        if (
            inspect.isfunction(value)
            or inspect.ismethod(value)
            or isinstance(value, (property, staticmethod, classmethod))
        ):
            members.append((name, value))
    return members


def _sc_render_symbol(root: str, name: str, obj: object) -> str:
    kind = _symbol_kind(obj)
    deprecation = _deprecation_of(importlib.import_module(root), obj)
    suffix = " · deprecated" if deprecation is not None else ""
    out = [f"## `{name}` — _{kind}_{suffix}", "", f"**Stability:** {_sc_badge(obj)}", ""]
    if deprecation is not None:
        out += [_deprecation_sentence(deprecation), ""]

    if inspect.isclass(obj):
        bases = [b.__name__ for b in obj.__bases__ if b is not object]
        header = f"class {name}({', '.join(bases)})" if bases else f"class {name}"
        init = obj.__dict__.get("__init__")
        init_sig = _sc_signature(obj) if init is not None else None
        code = header + (f"\n{name}{init_sig}" if init_sig else "")
        out += ["```python", code, "```", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc:
            out += [doc, ""]
        methods = _sc_public_members(obj)
        if methods:
            out += ["**Members**", ""]
            for mname, mval in methods:
                target = (
                    mval.fget
                    if isinstance(mval, property)
                    else (mval.__func__ if isinstance(mval, (staticmethod, classmethod)) else mval)
                )
                sig = _sc_signature(target) or ""
                summary = _sc_firstline(inspect.getdoc(target))
                tier = _sc_badge(target)
                line = f"- `{mname}{sig}` — {tier}"
                if summary:
                    line += f" — {summary}"
                out.append(line)
            out.append("")
    elif inspect.isroutine(obj):
        sig = _sc_signature(obj) or "(...)"
        out += ["```python", f"{name}{sig}", "```", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc:
            out += [doc, ""]
    else:
        out += [f"_{kind}_ — see the module source for the value.", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc and doc != inspect.getdoc(type(obj)):
            out += [doc, ""]
    return "\n".join(out)


def _sc_render_root_page(root: str) -> tuple[str, int]:
    module = importlib.import_module(root)
    public = sorted(getattr(module, "__all__", []))
    body = [
        _GENERATED_BANNER,
        f"# `{root}`\n",
        f"Canonical import root: `from {root} import ...`\n",
    ]
    root_deprecation = get_deprecation(module)
    if root_deprecation is not None:
        body.append(f"> **Deprecated.** {_root_deprecation_sentence(root_deprecation)}\n")
    body += [
        f"Self-contained public-API reference — {len(public)} symbols from this "
        "module's `__all__`, with signatures and docstrings inlined. "
        "Generated; do not hand-edit.\n",
    ]
    for name in public:
        body.append(_sc_render_symbol(root, name, getattr(module, name)))
    return "\n".join(body) + "\n", len(public)


def _sc_render_index(stats: list[tuple[str, int]]) -> str:
    version = _core_version()
    lines = [
        _GENERATED_BANNER,
        "# SciStudio API reference\n",
        f"**Version:** `{version}` (reference for this release).\n",
        "The public API you may rely on, generated from the code's docstrings and "
        "`scistudio.stability` decorators. Only the public surface (each canonical "
        "root's `__all__`) appears; `internal` symbols are excluded. Import from the "
        "canonical root shown on each page, never a deeper module path.\n",
        *_workflow_reference().index_lines(),
        "## Stability\n",
        "- `stable` — supported; no incompatible change within a major version "
        "without deprecation.\n"
        "- `provisional` — usable, may change in a minor release.\n"
        "- `internal` — excluded from this reference.\n",
        "A symbol marked **deprecated** keeps its tier and keeps working until "
        "the release its notice names removes it; the notice names the "
        "replacement.\n",
        "## Canonical roots\n",
    ]
    for root, count in stats:
        note = " — **deprecated**" if _root_is_deprecated(root) else ""
        lines.append(f"- [`{root}`]({root}.md) — {count} symbols{note}")
    lines.append("")
    lines += _panel_reference().index_section()
    return "\n".join(lines) + "\n"


def _panel_reference() -> Any:
    """The panel contract generator (ADR-052 Addendum 1), which lives beside this script."""
    here = str(Path(__file__).resolve().parent)
    if here not in sys.path:
        sys.path.insert(0, here)
    return importlib.import_module("build_panel_reference")


def generate_selfcontained() -> list[tuple[str, int]]:
    """Generate the self-contained reference under ``PACKAGE_REFERENCE_DIR`` (#1850)."""
    PACKAGE_REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    _workflow_reference().generate(PACKAGE_REFERENCE_DIR)
    stats: list[tuple[str, int]] = []
    for root in CANONICAL_ROOTS:
        page, count = _sc_render_root_page(root)
        _write_page(PACKAGE_REFERENCE_DIR / f"{root}.md", page)
        stats.append((root, count))
        print(f"  [self-contained] wrote {root}.md  ({count} symbols)")
    _panel_reference().generate(PACKAGE_REFERENCE_DIR)
    _write_page(PACKAGE_REFERENCE_DIR / "index.md", _sc_render_index(stats))
    print(f"  [self-contained] wrote index.md  (version {_core_version()})")
    return stats


def generate() -> list[tuple[str, int, int]]:
    """Generate index + per-root pages under ``docs/user/reference/``."""
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    stats: list[tuple[str, int, int]] = []
    for root in CANONICAL_ROOTS:
        page, public_count, marked = _render_root_page(root)
        _write_page(REFERENCE_DIR / f"{root}.md", page)
        stats.append((root, public_count, marked))
        print(f"  wrote {root}.md  ({public_count} public, {marked} marked)")
    _write_page(REFERENCE_DIR / "index.md", _render_index(stats))
    print(f"  wrote index.md  (version {_core_version()})")
    return stats


def build_strict() -> int:
    """Run ``mkdocs build --strict`` into the gitignored build dir."""
    cmd = [
        sys.executable,
        "-m",
        "mkdocs",
        "build",
        "--strict",
        "--config-file",
        str(MKDOCS_CONFIG),
        "--site-dir",
        str(SITE_DIR),
    ]
    print(f"  $ {' '.join(cmd)}")
    return subprocess.call(cmd, cwd=str(REPO_ROOT))


def _write_page(path: Path, text: str) -> None:
    """Write a generated page the way the repository stores every other file.

    Two properties the generator did not previously guarantee, both of which
    surfaced only when a version bump forced a regeneration (#2162):

    * a trailing newline, which pre-commit's end-of-file-fixer requires and
      which the templates do not reliably produce;
    * LF endings, because Path.write_text without an explicit newline uses the
      platform default and a regeneration on Windows would otherwise rewrite
      every page to CRLF.

    Hand-fixing the output instead would not survive the next regeneration --
    each page opens with "Do not hand-edit; regenerate".
    """

    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Generate the reference Markdown but skip the mkdocs --strict build.",
    )
    args = parser.parse_args(argv)

    print("Generating ADR-052 §7 public API reference ...")
    generate()
    print("Generating self-contained reference (#1850) ...")
    generate_selfcontained()
    if args.generate_only:
        print("Generated (skipped mkdocs build).")
        return 0
    rc = build_strict()
    if rc == 0:
        print(f"mkdocs build --strict OK -> {SITE_DIR}")
    else:
        print(f"mkdocs build --strict FAILED (exit {rc})", file=sys.stderr)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
