#!/usr/bin/env python3
"""Generate the workflow YAML file format reference from the workflow models.

A workflow file is a public contract that is not a Python API, so the Python
reference generator (``build_reference.py``) cannot see it. This module reads
the contract from the code that loads, saves, and validates workflow files and
renders one self-contained Markdown page, ``workflow-yaml.md``, into the
packaged API reference:

* the key tables come from ``WorkflowFileModel.model_json_schema()``: key order,
  type, required keys, defaults, and each key's ``Field(description=...)``;
* each section's summary is the docstring of the model that defines it;
* the load-time rules are the docstrings of the models' field validators;
* the handling of unlisted keys is read from each model's ``extra`` setting;
* the example files are built as ``WorkflowDefinition`` objects and written by
  the serializer that saves workflows (``dump_yaml_str``);
* the file name and run identity rules are the ``scistudio.workflow.identity``
  module docstring;
* the validation checks and the draft mode are read from the docstring of
  ``scistudio.workflow.validator.validate_workflow``;
* the full JSON Schema is embedded as generated.

The generator refuses to render a contract its code does not describe: a model
without its own docstring, a key without a description, or a field validator
without a docstring raises :class:`WorkflowReferenceError`. The committed page is
compared with a fresh render by ``tests/docs/test_workflow_reference.py``.

Run (never ``pip install -e .``)::

    PYTHONPATH=$PWD/src python scripts/docs/build_workflow_reference.py
"""

from __future__ import annotations

import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from pydantic import BaseModel  # noqa: E402

from scistudio.workflow import identity as identity_module  # noqa: E402
from scistudio.workflow import schema as schema_module  # noqa: E402
from scistudio.workflow.definition import (  # noqa: E402
    EdgeDef,
    ExposedPort,
    ExposedPorts,
    NodeDef,
    WorkflowDefinition,
)
from scistudio.workflow.serializer import dump_yaml_str  # noqa: E402
from scistudio.workflow.validator import validate_workflow  # noqa: E402

OUTPUT_DIR = SRC / "scistudio" / "_user_guide" / "api-reference"
PAGE = "workflow-yaml.md"
TITLE = "Workflow YAML file format"
STABILITY = "provisional"
ROOT_MODEL: type[BaseModel] = schema_module.WorkflowFileModel

_BANNER = (
    "<!-- GENERATED by scripts/docs/build_workflow_reference.py. "
    "Do not hand-edit; regenerate from the workflow models. -->\n"
)

#: How each pydantic ``extra`` setting treats keys a model does not declare.
_EXTRA_POLICY: dict[str, str] = {
    "ignore": "Keys not listed here are ignored when the file loads and are not written back when it is saved.",
    "forbid": "Keys not listed here are refused when the file loads.",
    "allow": "Keys not listed here are kept as written.",
}

_SPHINX_ROLE_RE = re.compile(r":[a-zA-Z]+:`~?([^`]+)`")
_RST_LITERAL_RE = re.compile(r"``(.+?)``")
_NUMBERED_ITEM_RE = re.compile(r"^(\d+(?:\.\d+)?)\.\s+(.*)$")


class WorkflowReferenceError(ValueError):
    """The workflow models do not describe part of the file format."""


# --------------------------------------------------------------------------
# Text helpers
# --------------------------------------------------------------------------


def _md(text: str) -> str:
    """Convert reStructuredText inline markup used in docstrings to Markdown."""
    text = _SPHINX_ROLE_RE.sub(lambda m: f"`{m.group(1).rsplit('.', 1)[-1]}`", text)
    return _RST_LITERAL_RE.sub(r"`\1`", text)


def _cell(text: str) -> str:
    """Make *text* safe inside one Markdown table cell."""
    return _md(" ".join(text.split())).replace("|", "\\|")


def _own_docstring(obj: Any, label: str) -> str:
    doc = obj.__dict__.get("__doc__") if isinstance(obj, type) else getattr(obj, "__doc__", None)
    if not doc or not doc.strip():
        raise WorkflowReferenceError(f"{label} has no docstring of its own")
    return inspect.cleandoc(doc)


def _unwrap_paragraphs(text: str) -> str:
    """Join hard-wrapped docstring lines into paragraphs and list items."""
    blocks: list[str] = []
    current: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            if current:
                blocks.append(" ".join(current))
                current = []
            continue
        if line.startswith(("* ", "- ")) and current:
            blocks.append(" ".join(current))
            current = []
        current.append(line)
    if current:
        blocks.append(" ".join(current))
    out: list[str] = []
    for block in blocks:
        if block.startswith("* "):
            block = "- " + block[2:]
        out.append(_md(block))
    # Consecutive list items stay together; other blocks are separated by a blank line.
    joined: list[str] = []
    for block in out:
        if joined and not (block.startswith("- ") and joined[-1].startswith("- ")):
            joined.append("")
        joined.append(block)
    return "\n".join(joined)


# --------------------------------------------------------------------------
# Schema walk
# --------------------------------------------------------------------------


def json_schema() -> dict[str, Any]:
    """The JSON Schema of a workflow file, as the loader's model defines it."""
    return ROOT_MODEL.model_json_schema()


def _models_by_name() -> dict[str, type[BaseModel]]:
    models: dict[str, type[BaseModel]] = {}
    for value in vars(schema_module).values():
        if isinstance(value, type) and issubclass(value, BaseModel) and value.__module__ == schema_module.__name__:
            models[value.__name__] = value
    return models


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _child_refs(prop: dict[str, Any]) -> list[tuple[str, str]]:
    """``(definition name, path suffix)`` for each model a property holds."""
    if "$ref" in prop:
        return [(_ref_name(prop["$ref"]), "")]
    if prop.get("type") == "array" and isinstance(prop.get("items"), dict):
        return [(name, "[]" + suffix) for name, suffix in _child_refs(prop["items"])]
    found: list[tuple[str, str]] = []
    for option in prop.get("anyOf", []):
        found.extend(_child_refs(option))
    return found


def sections() -> list[tuple[str, str]]:
    """Every model in the file, in reading order, as ``(definition name, key path)``."""
    schema = json_schema()
    root = schema["title"]
    paths: dict[str, list[str]] = {root: [""]}
    queue = [(schema, "")]
    while queue:
        node, path = queue.pop(0)
        for key, prop in node.get("properties", {}).items():
            for name, suffix in _child_refs(prop):
                child_path = f"{path}.{key}{suffix}" if path else f"{key}{suffix}"
                if name in paths:
                    paths[name].append(child_path)
                    continue
                paths[name] = [child_path]
                queue.append((schema["$defs"][name], child_path))
    return [(name, " / ".join(f"`{p}`" for p in found if p)) for name, found in paths.items()]


def _definition(schema: dict[str, Any], name: str) -> dict[str, Any]:
    return schema if name == schema["title"] else schema["$defs"][name]


def _heading(name: str, path: str) -> str:
    label = name.removesuffix("Model")
    return f"{path} — {label}" if path else f"The file — {label}"


def _anchor(heading: str) -> str:
    slug = heading.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"\s+", "-", slug.strip())


def _type_text(prop: dict[str, Any], links: dict[str, str]) -> str:
    if "$ref" in prop:
        name = _ref_name(prop["$ref"])
        return f"[{name.removesuffix('Model')}](#{links[name]})"
    if "anyOf" in prop:
        options = [o for o in prop["anyOf"] if o.get("type") != "null"]
        text = " or ".join(_type_text(o, links) for o in options)
        return f"{text} or null" if len(options) < len(prop["anyOf"]) else text
    kind = prop.get("type")
    if kind == "array":
        return f"list of {_type_text(prop.get('items', {}), links)}"
    if kind == "object":
        values = prop.get("additionalProperties")
        if isinstance(values, dict) and values:
            return f"mapping of string to {_type_text(values, links)}"
        return "mapping"
    return {"string": "string", "number": "number", "integer": "integer", "boolean": "boolean"}.get(str(kind), "any")


# --------------------------------------------------------------------------
# Page sections
# --------------------------------------------------------------------------


def _model_section(name: str, path: str, schema: dict[str, Any], links: dict[str, str]) -> list[str]:
    model = _models_by_name()[name]
    definition = _definition(schema, name)
    heading = _heading(name, path)
    out = [f"## {heading}", "", _unwrap_paragraphs(_own_docstring(model, name)), ""]

    required = set(definition.get("required", []))
    out += ["| Key | Type | Required | Default | Description |", "|---|---|---|---|---|"]
    for key, prop in definition.get("properties", {}).items():
        description = prop.get("description")
        if not description:
            raise WorkflowReferenceError(f"{name}.{key} has no description")
        default = "—" if key in required or "default" not in prop else f"`{json.dumps(prop['default'])}`"
        out.append(
            f"| `{key}` | {_type_text(prop, links)} | {'yes' if key in required else 'no'} | {default} | "
            f"{_cell(description)} |"
        )
    out.append("")

    rules: list[str] = []
    for decorator in model.__pydantic_decorators__.field_validators.values():
        doc = _own_docstring(decorator.func, f"{name} validator {decorator.cls_var_name}")
        rules.append(f"- {_cell(doc)}")
    if rules:
        out += ["Checked when the file loads:", "", *rules, ""]

    extra = str(model.model_config.get("extra") or "ignore")
    out += [_EXTRA_POLICY[extra], ""]
    return out


def example_files() -> list[tuple[str, WorkflowDefinition]]:
    """The example files shown on the page, as the definitions SciStudio would save."""
    workflow = WorkflowDefinition(
        id="tidy-measurements",
        version="1.0.0",
        description="Load a table and export it through a reusable subworkflow.",
        nodes=[
            NodeDef(
                id="load",
                block_type="load_data",
                config={"core_type": "DataFrame", "path": "data/raw/measurements.csv"},
                layout={"x": 0.0, "y": 0.0},
            ),
            NodeDef(
                id="export",
                block_type="subworkflow_block",
                config={"ref": {"path": "subworkflows/export-table.yaml"}},
                layout={"x": 320.0, "y": 0.0},
            ),
        ],
        edges=[EdgeDef(source="load:data", target="export:table")],
    )
    subworkflow = WorkflowDefinition(
        id="export-table",
        version="1.0.0",
        description="Save a table under data/results.",
        nodes=[
            NodeDef(
                id="save",
                block_type="save_data",
                config={"core_type": "DataFrame", "path": "data/results"},
                layout={"x": 0.0, "y": 0.0},
            ),
        ],
        exposed_ports=ExposedPorts(inputs=[ExposedPort(name="table", internal="save.data")]),
    )
    return [
        ("workflows/tidy-measurements.yaml", workflow),
        ("subworkflows/export-table.yaml", subworkflow),
    ]


def _examples_section() -> list[str]:
    out = [
        "## Example",
        "",
        "A workflow that references a subworkflow, and the subworkflow file, as SciStudio saves them.",
        "",
    ]
    for path, definition in example_files():
        out += [f"`{path}`", "", "```yaml", dump_yaml_str(definition).rstrip(), "```", ""]
    return out


def _identity_section() -> list[str]:
    doc = _own_docstring(identity_module, "scistudio.workflow.identity")
    return ["## File name and run identity", "", _unwrap_paragraphs(doc), ""]


def _docstring_block(doc: str, start: str, stop: str) -> list[str]:
    lines = doc.splitlines()
    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == start) + 1
    except StopIteration as exc:
        raise WorkflowReferenceError(f"validate_workflow docstring has no {start!r} block") from exc
    end = next((i for i in range(begin, len(lines)) if lines[i].strip() == stop), len(lines))
    return lines[begin:end]


def _validation_checks(doc: str) -> list[str]:
    """The numbered checks, then any paragraph that follows the list."""
    items: list[str] = []
    after: list[str] = []
    for line in _docstring_block(doc, "Checks, in order:", "Parameters"):
        text = line.strip()
        if not text:
            continue
        match = _NUMBERED_ITEM_RE.match(text)
        if match and not after:
            items.append(match.group(2))
        elif items and line.startswith((" ", "\t")) and not after:
            items[-1] += " " + text
        else:
            after.append(text)
    if not items:
        raise WorkflowReferenceError("validate_workflow docstring lists no checks")
    out = [f"{number}. {_md(item.replace(' -- ', ' — '))}" for number, item in enumerate(items, start=1)]
    if after:
        out += ["", _md(" ".join(after))]
    return out


def _parameter_text(doc: str, name: str) -> str:
    lines = _docstring_block(doc, "Parameters", "Returns")
    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == f"{name}:") + 1
    except StopIteration as exc:
        raise WorkflowReferenceError(f"validate_workflow docstring does not document {name!r}") from exc
    body: list[str] = []
    for line in lines[begin:]:
        if line.strip() and not line.startswith((" ", "\t")):
            break
        body.append(line.strip())
    return _md(" ".join(part for part in body if part))


def _validation_section() -> list[str]:
    doc = inspect.cleandoc(validate_workflow.__doc__ or "")
    return [
        "## Validation",
        "",
        "Loading a file checks the shape described above. Validating a workflow — before a run starts, when the "
        "canvas saves, and through the `validate_workflow` agent tool — also checks the graph:",
        "",
        *_validation_checks(doc),
        "",
        f"Validation runs in one of two modes. {_parameter_text(doc, 'mode')}",
        "",
    ]


def _json_schema_section(schema: dict[str, Any]) -> list[str]:
    return [
        "## JSON Schema",
        "",
        "The JSON Schema of a workflow file, as generated from the loader's models.",
        "",
        "```json",
        json.dumps(schema, indent=2, ensure_ascii=False),
        "```",
        "",
    ]


def render_page() -> str:
    """Render ``workflow-yaml.md``."""
    schema = json_schema()
    order = sections()
    links = {name: _anchor(_heading(name, path)) for name, path in order}
    out = [
        _BANNER,
        f"# {TITLE}",
        "",
        f"**Stability:** `{STABILITY}` — the file format may change in a minor release.",
        "",
        "Generated from the models that load and save workflow files, the checks workflow validation runs, and "
        "the rules that tie a workflow to its file. Do not hand-edit.",
        "",
        "Contents:",
        "",
    ]
    out += [f"- [{_heading(name, path)}](#{links[name]})" for name, path in order]
    out.append("")
    out += _examples_section()
    for name, path in order:
        out += _model_section(name, path, schema, links)
    out += _identity_section()
    out += _validation_section()
    out += _json_schema_section(schema)
    return "\n".join(out).rstrip() + "\n"


def index_lines() -> list[str]:
    """The lines ``build_reference.py`` puts in the API reference index for this page."""
    return [
        f"The workflow file format has its own generated page: [{TITLE}]({PAGE}) (`{STABILITY}`) — the keys, "
        "rules, and JSON Schema of a workflow YAML file.\n",
    ]


def generate(output_dir: Path = OUTPUT_DIR) -> Path:
    """Write ``workflow-yaml.md`` into *output_dir* and return its path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / PAGE
    target.write_text(render_page(), encoding="utf-8", newline="\n")
    print(f"  [self-contained] wrote {PAGE}")
    return target


def main() -> int:
    generate()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
