#!/usr/bin/env python3
"""Generate the panel API reference from the panel SDK sources (ADR-052 Addendum 1).

The panel contract is not Python, so the Python reference generator
(``build_reference.py``) cannot see it. This module reads the contract from the
files that implement it and renders three self-contained Markdown pages into
the packaged API reference:

* ``panels-sdk.md`` -- ``window.scistudio`` from JSDoc blocks in
  ``sdk/<major>/scistudio-panel.js``, the per-context operations from
  ``PanelContext.provides``, the read operations from
  ``scistudio.panels.reads.READ_OPERATIONS``, and the pinned libraries from
  ``panels/lib/index.json``.
* ``panels-renderers.md`` -- the stylesheets and the components exported by
  ``panel-ui.js`` and re-exported by ``renderers.js``, from their JSDoc blocks;
  prop defaults are read from the component signatures.
* ``panel-descriptor.md`` -- the ``panel.json`` schema from
  ``scistudio.panels.descriptor.DESCRIPTOR_FIELDS`` and the ``panel.sample.json``
  shape from the SDK's ``@sample`` block.

JSDoc conventions (only ``/** ... */`` blocks are read):

* Tags are one line each; every non-tag line is description.
* ``@overview`` marks a file's overview block.
* An exported component's block sits directly above ``export function Name(``
  and documents its props as ``@param {type} [props.name] description``
  (brackets mark an optional prop). Defaults come from the signature.
* An SDK member's block carries ``@member name`` and optionally ``@group``,
  ``@context``, ``@type``, ``@param``, and ``@returns``.
* The SDK's ``@errors`` block lists ``@error code description``; its ``@sample``
  block lists ``@property {type} [name] description``.

The generator refuses to render a contract that disagrees with its code: an
undocumented export or SDK member, a documented prop the component does not
take, an SDK error code without a description, or a sample key the SDK does
not read all raise :class:`PanelReferenceError`. The committed pages are
compared with a fresh render by ``tests/docs/test_panel_reference.py``.

Run (never ``pip install -e .``)::

    PYTHONPATH=$PWD/src python scripts/docs/build_panel_reference.py
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from types import SimpleNamespace
from typing import cast

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from scistudio.panels.contexts import PanelContext  # noqa: E402
from scistudio.panels.descriptor import (  # noqa: E402
    DESCRIPTOR_FIELDS,
    DESCRIPTOR_FILE_RULES,
    PANEL_API_MAJOR,
    PANEL_API_VERSION,
    PANEL_CONTEXTS,
)
from scistudio.panels.reads import READ_OPERATIONS  # noqa: E402

PANELS_DIR = SRC / "scistudio" / "panels"
SDK_DIR = PANELS_DIR / "sdk" / PANEL_API_MAJOR
LIB_INDEX = PANELS_DIR / "lib" / "index.json"
OUTPUT_DIR = SRC / "scistudio" / "_user_guide" / "api-reference"

SDK_PAGE = "panels-sdk.md"
RENDERERS_PAGE = "panels-renderers.md"
DESCRIPTOR_PAGE = "panel-descriptor.md"

STABILITY = "provisional"

_BANNER = (
    "<!-- GENERATED by scripts/docs/build_panel_reference.py. "
    "Do not hand-edit; regenerate from the panel SDK sources. -->\n"
)


class PanelReferenceError(ValueError):
    """The panel sources and their documentation disagree."""


# --------------------------------------------------------------------------
# JSDoc parsing
# --------------------------------------------------------------------------

_BLOCK = re.compile(r"/\*\*(.*?)\*/", re.S)
_TAG = re.compile(r"@(\w+)\s*(.*)")


@dataclass
class Param:
    name: str
    type: str
    optional: bool
    description: str


@dataclass
class DocBlock:
    description: str
    tags: dict[str, list[str]]
    end: int
    params: list[Param] = field(default_factory=list)

    def first(self, tag: str) -> str | None:
        values = self.tags.get(tag)
        return values[0] if values else None


def _block_lines(raw: str) -> list[str]:
    lines = []
    for line in raw.split("\n"):
        stripped = line.strip()
        if stripped.startswith("*"):
            stripped = stripped[1:]
            if stripped.startswith(" "):
                stripped = stripped[1:]
        lines.append(stripped.rstrip())
    return lines


def _split_type(text: str) -> tuple[str, str] | None:
    """Split ``{type} rest`` where the type may itself contain braces."""
    text = text.strip()
    if not text.startswith("{"):
        return None
    depth = 0
    for index, char in enumerate(text):
        depth += {"{": 1, "}": -1}.get(char, 0)
        if depth == 0:
            return text[1:index].strip(), text[index + 1 :].strip()
    return None


def _param(text: str, *, where: str) -> Param:
    split = _split_type(text)
    match = re.fullmatch(r"(?P<name>\[[^\]]+\]|\S+)\s*(?P<desc>.*)", split[1]) if split else None
    if split is None or match is None:
        raise PanelReferenceError(f"{where}: malformed tag {text!r}; expected '{{type}} name description'")
    name = match["name"]
    optional = name.startswith("[")
    return Param(name.strip("[]"), split[0], optional, match["desc"].strip())


def parse_blocks(source: str, *, where: str) -> list[DocBlock]:
    """Every ``/** ... */`` block in ``source``, split into description and tags."""
    blocks: list[DocBlock] = []
    for match in _BLOCK.finditer(source):
        description: list[str] = []
        tags: dict[str, list[str]] = {}
        in_fence = False
        for line in _block_lines(match.group(1)):
            if line.startswith("```"):
                in_fence = not in_fence
            tag = None if in_fence else _TAG.match(line)
            if tag:
                tags.setdefault(tag.group(1), []).append(tag.group(2).strip())
            else:
                description.append(line)
        text = "\n".join(description).strip("\n")
        block = DocBlock(re.sub(r"\n{3,}", "\n\n", text), tags, match.end())
        block.params = [_param(p, where=where) for p in tags.get("param", []) + tags.get("property", [])]
        blocks.append(block)
    return blocks


def _matching(source: str, start: int, open_char: str, close_char: str) -> int:
    """Index just past the bracket that closes the one at ``start``."""
    depth = 0
    quote: str | None = None
    index = start
    while index < len(source):
        char = source[index]
        if quote:
            if char == "\\":
                index += 1
            elif char == quote:
                quote = None
        elif source.startswith("//", index):
            index = source.find("\n", index)
            if index < 0:
                break
        elif source.startswith("/*", index):
            index = source.find("*/", index) + 1
            if index <= 0:
                break
        elif char in "\"'`":
            quote = char
        elif char == open_char:
            depth += 1
        elif char == close_char:
            depth -= 1
            if depth == 0:
                return index + 1
        index += 1
    raise PanelReferenceError(f"unbalanced {open_char}{close_char} at offset {start}")


def _split_top_level(text: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    quote: str | None = None
    current: list[str] = []
    for index, char in enumerate(text):
        if quote:
            current.append(char)
            if char == quote and text[index - 1] != "\\":
                quote = None
            continue
        if char in "\"'`":
            quote = char
        elif char in "([{":
            depth += 1
        elif char in ")]}":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(char)
    parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


@dataclass
class Signature:
    """A component's destructured props: name -> default source (``None`` when none)."""

    props: dict[str, str | None] | None
    has_rest: bool


def parse_signature(parameters: str) -> Signature:
    """Read the props a component destructures, and their defaults."""
    text = parameters.strip()
    if not text.startswith("{"):
        return Signature(None, False)
    props: dict[str, str | None] = {}
    has_rest = False
    for part in _split_top_level(text[1 : _matching(text, 0, "{", "}") - 1]):
        if part.startswith("..."):
            has_rest = True
            continue
        name, _, default = part.partition("=")
        key = name.split(":")[0].strip()
        props[key] = default.strip() or None
    return Signature(props, has_rest)


@dataclass
class Component:
    name: str
    module: str
    doc: DocBlock | None
    signature: Signature


def _exported_components(path: Path) -> dict[str, Component]:
    source = path.read_text(encoding="utf-8")
    blocks = parse_blocks(source, where=path.name)
    components: dict[str, Component] = {}
    for match in re.finditer(r"^export function (\w+)\s*\(", source, re.M):
        name = match.group(1)
        doc = next((b for b in blocks if b.end <= match.start() and not source[b.end : match.start()].strip()), None)
        open_paren = match.end() - 1
        parameters = source[open_paren + 1 : _matching(source, open_paren, "(", ")") - 1]
        components[name] = Component(name, path.name, doc, parse_signature(parameters))
    return components


def _check_component(component: Component) -> None:
    where = f"{component.module}: {component.name}"
    if component.doc is None or not component.doc.description:
        raise PanelReferenceError(f"{where} is exported without a JSDoc description")
    documented = []
    for param in component.doc.params:
        if not param.name.startswith("props."):
            raise PanelReferenceError(f"{where}: document props as 'props.<name>', got {param.name!r}")
        documented.append(param.name[len("props.") :])
    props = component.signature.props
    if props is None:
        return
    missing = sorted(set(props) - set(documented))
    extra = sorted(set(documented) - set(props))
    if missing or extra:
        raise PanelReferenceError(f"{where}: props undocumented {missing}, documented but not taken {extra}")


def _overview(path: Path) -> str:
    blocks = [b for b in parse_blocks(path.read_text(encoding="utf-8"), where=path.name) if "overview" in b.tags]
    if len(blocks) != 1:
        raise PanelReferenceError(f"{path.name}: expected exactly one @overview block, found {len(blocks)}")
    return blocks[0].description


def _re_exports(path: Path) -> list[tuple[str, str]]:
    source = path.read_text(encoding="utf-8")
    return re.findall(r'^export \{\s*(\w+)\s*\} from "\./([\w.-]+)";', source, re.M)


# --------------------------------------------------------------------------
# Rendering helpers
# --------------------------------------------------------------------------


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _stamp() -> str:
    return (
        f"> **Stability:** `{STABILITY}` · **Panel API version:** `{PANEL_API_VERSION}` · "
        f"**SDK path:** `sdk/{PANEL_API_MAJOR}/`\n"
    )


def _props_table(component: Component) -> list[str]:
    assert component.doc is not None
    if not component.doc.params:
        return ["Takes no props.", ""]
    rows = ["| Prop | Type | Default | Description |", "| --- | --- | --- | --- |"]
    defaults = component.signature.props or {}
    for param in component.doc.params:
        name = param.name[len("props.") :]
        default = defaults.get(name)
        shown = f"`{_cell(default)}`" if default is not None else ("optional" if param.optional else "**required**")
        rows.append(f"| `{name}` | `{_cell(param.type)}` | {shown} | {_cell(param.description)} |")
    lines = [*rows, ""]
    if component.signature.has_rest:
        lines += ["Other props are passed to the root element.", ""]
    return lines


# --------------------------------------------------------------------------
# panels-sdk.md
# --------------------------------------------------------------------------

_SDK_GROUPS = ("Lifecycle", "Context properties", "View state and theme", "Data", "Decisions", "Python", "Services")


def _sdk_api_names(source: str) -> set[str]:
    names = set(re.findall(r"\bapi\.(\w+)\s*=(?!=)", source))
    literal = re.search(r"var api = \{", source)
    if literal is None:
        raise PanelReferenceError("scistudio-panel.js: 'var api = {' not found")
    start = literal.end() - 1
    body = source[start : _matching(source, start, "{", "}")]
    names |= set(re.findall(r"^\s{4}(\w+):\s*function\b", body, re.M))
    return names


def _sdk_signature(source: str, name: str) -> str | None:
    match = re.search(rf"\bapi\.{name}\s*=\s*function\s*\(([^)]*)\)", source) or re.search(
        rf"^\s+{name}:\s*function\s*\(([^)]*)\)", source, re.M
    )
    return f"{name}({match.group(1).strip()})" if match else None


def _provides(kind: str, *, has_python: bool) -> tuple[list[str], list[str]]:
    """What ``PanelContext.provides`` grants a context of ``kind``; it reads only these two fields."""
    stand_in = cast("PanelContext", SimpleNamespace(kind=kind, panel=SimpleNamespace(has_python=has_python)))
    return PanelContext.provides(stand_in)


def _context_table() -> list[str]:
    rows = ["| Context | Operations | Services |", "| --- | --- | --- |"]
    for kind in PANEL_CONTEXTS:
        with_python = _provides(kind, has_python=True)
        without = _provides(kind, has_python=False)
        operations = []
        for op in with_python[0]:
            operations.append(f"`{op}`" if op in without[0] else f"`{op}` (with `panel.py`)")
        services = ", ".join(f"`{s}`" for s in with_python[1])
        rows.append(f"| `{kind}` | {', '.join(operations)} | {services} |")
    return [*rows, ""]


def _libraries() -> list[str]:
    index = json.loads(LIB_INDEX.read_text(encoding="utf-8"))
    rows = ["| Library | Version | Files |", "| --- | --- | --- |"]
    for library in index["libraries"]:
        files = ", ".join(
            f"`{library['name']}@{library['version']}/{f}`"
            for f in library["files"]
            if f.endswith((".js", ".mjs")) and f.split("/")[0] in ("dist", "build")
        )
        rows.append(f"| {library['name']} | `{library['version']}` | {files} |")
    return [*rows, ""]


def render_sdk_page() -> str:
    path = SDK_DIR / "scistudio-panel.js"
    source = path.read_text(encoding="utf-8")
    blocks = parse_blocks(source, where=path.name)

    sample_version = re.search(r'apiVersion:\s*"([^"]+)"', source)
    if sample_version is None or sample_version.group(1) != PANEL_API_VERSION:
        raise PanelReferenceError(
            f"scistudio-panel.js sample mode reports apiVersion {sample_version and sample_version.group(1)!r}, "
            f"the host serves {PANEL_API_VERSION!r}"
        )

    members = {str(b.first("member")): b for b in blocks if "member" in b.tags}
    names = _sdk_api_names(source)
    if set(members) != names:
        raise PanelReferenceError(
            f"scistudio-panel.js: undocumented members {sorted(names - set(members))}, "
            f"documented but absent {sorted(set(members) - names)}"
        )
    out = [
        _BANNER,
        "# Panel SDK: `window.scistudio`\n",
        _stamp(),
        _overview(path) + "\n",
        "## Contexts\n",
        "What `window.scistudio` offers depends on the context. Operations and services "
        "a context does not provide are absent.\n",
        *_context_table(),
    ]
    for group in _SDK_GROUPS:
        in_group = [(n, b) for n, b in members.items() if (b.first("group") or "") == group]
        if not in_group:
            continue
        out.append(f"## {group}\n")
        for name, block in in_group:
            signature = _sdk_signature(source, str(name))
            heading = f"### `scistudio.{signature or name}`"
            out.append(heading + "\n")
            facts = []
            declared = block.first("type")
            if declared:
                split = _split_type(declared)
                if split is None:
                    raise PanelReferenceError(f"scistudio-panel.js {name}: malformed @type {declared!r}")
                facts.append(f"**Type:** `{split[0]}`")
            if block.first("context"):
                contexts = ", ".join(f"`{c.strip()}`" for c in str(block.first("context")).split(","))
                facts.append(f"**Contexts:** {contexts}")
            if facts:
                out.append(" · ".join(facts) + "\n")
            out.append(block.description + "\n")
            if block.params:
                out += ["| Parameter | Type | Description |", "| --- | --- | --- |"]
                for param in block.params:
                    label = f"`{param.name}`" + (" (optional)" if param.optional else "")
                    out.append(f"| {label} | `{_cell(param.type)}` | {_cell(param.description)} |")
                out.append("")
            returns = block.first("returns")
            if returns:
                split = _split_type(returns)
                if split is None:
                    raise PanelReferenceError(f"scistudio-panel.js {name}: malformed @returns {returns!r}")
                tail = f" — {split[1]}" if split[1] else ""
                out.append(f"**Returns:** `{split[0]}`{tail}\n")
    ungrouped = sorted(str(n) for n, b in members.items() if b.first("group") not in _SDK_GROUPS)
    if ungrouped:
        raise PanelReferenceError(f"scistudio-panel.js: members without a known @group: {ungrouped}")

    out += [
        "## Read operations\n",
        "`scistudio.read(op, params)` accepts these operations. A parameter not listed is refused "
        'with `invalid_request`. Every operation also accepts `format`: `"json"` (the default) or '
        '`"binary"` for the array and series reads.\n',
        "| Operation | Target | Parameters | Result |",
        "| --- | --- | --- | --- |",
    ]
    for operation in READ_OPERATIONS.values():
        if operation.params is None:
            params = "_ignored_"
        elif not operation.params:
            params = "none"
        else:
            params = ", ".join(f"`{p}`" for p in operation.params)
        out.append(f"| `{operation.op}` | {operation.target} | {params} | {_cell(operation.result)} |")
    out.append("")

    error_blocks = [b for b in blocks if "errors" in b.tags]
    if len(error_blocks) != 1:
        raise PanelReferenceError("scistudio-panel.js: expected exactly one @errors block")
    documented_errors: dict[str, str] = {}
    for entry in error_blocks[0].tags.get("error", []):
        code, _, description = entry.partition(" ")
        documented_errors[code] = description.strip()
    raised = set(re.findall(r'failure\("(\w+)"', source))
    if raised != set(documented_errors):
        raise PanelReferenceError(
            f"scistudio-panel.js: error codes undocumented {sorted(raised - set(documented_errors))}, "
            f"documented but never raised {sorted(set(documented_errors) - raised)}"
        )
    out += ["## Errors\n", error_blocks[0].description + "\n", "| Code | Meaning |", "| --- | --- |"]
    out += [f"| `{code}` | {_cell(text)} |" for code, text in documented_errors.items()]
    out.append("")

    out += [
        "## Shared libraries\n",
        "Pinned third-party libraries served beside the SDK. Import them by relative path from the "
        "panel page (`../../lib/<name>@<version>/<file>`) or from `scistudio.libBaseUrl`.\n",
        *_libraries(),
        "## Sample mode\n",
        f"Opened outside a SciStudio frame, the SDK answers from `panel.sample.json`; its shape is in "
        f"[the panel descriptor reference]({DESCRIPTOR_PAGE}#panelsamplejson).\n",
    ]
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# panels-renderers.md
# --------------------------------------------------------------------------


def _css_tokens() -> list[str]:
    tokens: set[str] = set()
    for sheet in ("panel.css", "renderers.css"):
        tokens |= set(re.findall(r"var\((--ss-[a-z0-9-]+)", (SDK_DIR / sheet).read_text(encoding="utf-8")))
    return sorted(tokens)


def _component_section(component: Component) -> list[str]:
    _check_component(component)
    assert component.doc is not None
    return [f"### `{component.name}`\n", component.doc.description + "\n", *_props_table(component)]


def render_renderers_page() -> str:
    ui_path = SDK_DIR / "panel-ui.js"
    renderers_path = SDK_DIR / "renderers.js"
    ui = _exported_components(ui_path)
    out = [
        _BANNER,
        "# Panel components and stylesheets\n",
        _stamp(),
        "## Stylesheets\n",
        "### `panel.css`\n",
        _overview(SDK_DIR / "panel.css") + "\n",
        "### `renderers.css`\n",
        _overview(SDK_DIR / "renderers.css") + "\n",
        "### Theme tokens\n",
        "The SDK copies the host's `--ss-*` theme tokens onto the panel's root element and sets "
        "`data-theme` to `light` or `dark`. The stylesheets read these tokens, as space-separated "
        "RGB channels, with fallbacks for sample mode.\n",
        *[f"- `{token}`" for token in _css_tokens()],
        "",
        f"## UI components: `sdk/{PANEL_API_MAJOR}/panel-ui.js`\n",
        _overview(ui_path) + "\n",
    ]
    for component in ui.values():
        out += _component_section(component)

    out += [f"## Data views: `sdk/{PANEL_API_MAJOR}/renderers.js`\n", _overview(renderers_path) + "\n"]
    exports = _re_exports(renderers_path)
    if not exports:
        raise PanelReferenceError("renderers.js re-exports nothing")
    cache: dict[str, dict[str, Component]] = {}
    for name, module in exports:
        components = cache.setdefault(module, _exported_components(SDK_DIR / module))
        if name not in components:
            raise PanelReferenceError(f"renderers.js re-exports {name} from {module}, which does not export it")
        component = components[name]
        section = _component_section(component)
        section.insert(1, f"Module: `sdk/{PANEL_API_MAJOR}/{module}`\n")
        out += section
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# panel-descriptor.md
# --------------------------------------------------------------------------


def _sample_keys_read(source: str) -> set[str]:
    return set(re.findall(r"(?<![\w.])(?:sample|loaded)\.(\w+)", source))


def render_descriptor_page() -> str:
    source = (SDK_DIR / "scistudio-panel.js").read_text(encoding="utf-8")
    samples = [b for b in parse_blocks(source, where="scistudio-panel.js") if "sample" in b.tags]
    if len(samples) != 1:
        raise PanelReferenceError("scistudio-panel.js: expected exactly one @sample block")
    sample = samples[0]
    documented = {p.name for p in sample.params}
    read = _sample_keys_read(source)
    if documented != read:
        raise PanelReferenceError(
            f"panel.sample.json: keys read but undocumented {sorted(read - documented)}, "
            f"documented but never read {sorted(documented - read)}"
        )

    out = [
        _BANNER,
        "# Panel descriptor: `panel.json`\n",
        _stamp(),
        "A panel is a directory holding `panel.json`, an HTML entry page, and optionally "
        "`panel.sample.json` and `panel.py`. `panel.json` declares what the panel is; the host "
        "validates it when panels are discovered and skips a panel whose descriptor is invalid, "
        "reporting why.\n",
        "## Keys\n",
        "| Key | Type | Required | Default | Rule |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in DESCRIPTOR_FIELDS:
        required = "yes" if entry.required else "no"
        default = entry.default or "—"
        out.append(f"| `{entry.key}` | {entry.json_type} | {required} | {default} | {_cell(entry.rule)} |")
    out += ["", "## Directory rules\n", *[f"- {rule}" for rule in DESCRIPTOR_FILE_RULES], ""]
    out += ["## Contexts\n"]
    out += [
        "- `preview` — shows a data object in the preview area.",
        "- `interactive` — the window an interactive block opens to collect a decision.",
        "- `miniapp` — a standalone app over one type, optionally backed by `panel.py`.",
        "",
        f"What each context may call is in [the panel SDK reference]({SDK_PAGE}#contexts).\n",
    ]
    if {line.split("`")[1] for line in out if line.startswith("- `") and "—" in line} != set(PANEL_CONTEXTS):
        raise PanelReferenceError("panel-descriptor.md: the context list disagrees with PANEL_CONTEXTS")
    out += [
        "## `panel.sample.json`\n",
        sample.description + "\n",
        "| Key | Type | Description |",
        "| --- | --- | --- |",
    ]
    for param in sample.params:
        label = f"`{param.name}`" + (" (optional)" if param.optional else "")
        out.append(f"| {label} | `{_cell(param.type)}` | {_cell(param.description)} |")
    out.append("")
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# Entry points
# --------------------------------------------------------------------------

PAGES = {
    SDK_PAGE: ("Panel SDK", "`window.scistudio`: contexts, operations, read operations, errors, libraries"),
    RENDERERS_PAGE: ("Panel components", "stylesheets, UI components, and data views"),
    DESCRIPTOR_PAGE: ("Panel descriptor", "`panel.json` keys and rules, and `panel.sample.json`"),
}

_RENDERERS = {
    SDK_PAGE: render_sdk_page,
    RENDERERS_PAGE: render_renderers_page,
    DESCRIPTOR_PAGE: render_descriptor_page,
}


def render_pages() -> dict[str, str]:
    """Every panel reference page, keyed by file name."""
    return {name: render() for name, render in _RENDERERS.items()}


def index_section() -> list[str]:
    """The API reference index lines that link the panel pages."""
    lines = [
        "## Panel contract\n",
        f"The panel SDK, components, and descriptor (panel API `{PANEL_API_VERSION}`, `{STABILITY}`), "
        "generated from the panel sources.\n",
    ]
    lines += [f"- [{title}]({page}) — {summary}" for page, (title, summary) in PAGES.items()]
    lines.append("")
    return lines


def generate(output_dir: Path = OUTPUT_DIR) -> list[str]:
    """Write the panel reference pages; returns the file names written."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in render_pages().items():
        (output_dir / name).write_text(text, encoding="utf-8", newline="\n")
        written.append(name)
        print(f"  [panels] wrote {name}")
    return written


def main() -> int:
    print("Generating the panel API reference ...")
    generate()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
