#!/usr/bin/env python3
"""Generate the SciStudio public API reference (ADR-052 §7, spec §16 step 2).

The author-facing API reference is **generated from docstrings + the
``scistudio.stability`` decorators** so it cannot drift from the code and the
tier / ``Since`` badges render automatically rather than from a hand-maintained
table (ADR-052 §7).

What this script does:

1. Imports the **nine canonical public roots** (ADR-052 §3/§4; the SciStudio
   freeze contract) and, for each, reads its declared ``__all__`` — the public
   surface. Symbols outside ``__all__`` (and ``internal``-tier class members) are
   excluded even if they have docstrings.
2. For every public symbol it reads the stability tier and ``Since`` through the
   single read path :func:`scistudio.stability.get_stability` and renders a
   badge next to the entry.
3. Emits one Markdown page per root under ``docs/user/reference/`` plus a
   version-stamped ``index.md``. Each page contains an ``mkdocstrings``
   (``griffe``) autodoc directive per symbol, so ``mkdocstrings`` renders the
   docstring + signature while this script supplies the filter + badge.
4. Runs ``mkdocs build --strict`` (unless ``--generate-only``) so the reference
   provably builds green.

The generated pages under ``docs/user/reference/`` are a generated artifact
(ADR-042 generated-doc rule): regenerate with this script, do not hand-edit.

Run (never ``pip install -e .``)::

    PYTHONPATH=$PWD/src python scripts/docs/build_reference.py
    PYTHONPATH=$PWD/src python scripts/docs/build_reference.py --generate-only

``mike`` multi-version hosting is deferred (single-version stamp for alpha):

    TODO(#1817): multi-version published reference docs (mike) once >1 core line
      is supported. Out of scope per ADR-052 §7 (single-version generated docs
      for alpha). Followup: https://github.com/jiazhenz026/SciStudio/issues/1817
"""

from __future__ import annotations

import argparse
import enum
import importlib
import inspect
import re
import subprocess
import sys
import types
from pathlib import Path

#: Convert in-docstring Sphinx cross-reference roles (``:meth:`run```,
#: ``:class:`pandas.DataFrame```) into plain inline code for the self-contained
#: Markdown reference (the mkdocs site does the same via griffe_sphinx_roles.py).
_SPHINX_ROLE_RE = re.compile(r":[a-zA-Z]+:`~?([^`]+)`")


def _strip_sphinx_roles(text: str) -> str:
    return _SPHINX_ROLE_RE.sub(r"`\1`", text)


REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from scistudio.stability import get_stability  # noqa: E402

#: The nine canonical public roots. Public surface = each root's ``__all__``
#: (ADR-052 §3/§4; identical to the SciStudio freeze contract).
CANONICAL_ROOTS: tuple[str, ...] = (
    "scistudio.core.types",
    "scistudio.core.meta",
    "scistudio.blocks.base",
    "scistudio.blocks.process",
    "scistudio.blocks.io",
    "scistudio.blocks.app",
    "scistudio.blocks.code",
    "scistudio.previewers.models",
    "scistudio.previewers.data_access",
)

REFERENCE_DIR = REPO_ROOT / "docs" / "user" / "reference"
#: Self-contained reference (ADR-052 §7; #1850). Unlike ``REFERENCE_DIR`` (which
#: holds ``mkdocstrings`` directive shells that only render under an mkdocs
#: build), this directory holds **self-contained** Markdown with real signatures
#: and docstrings inlined, so it is readable as-is. It lives inside the package
#: so it ships in the wheel and is provisioned into ``<project>/user-guide/
#: api-reference/`` for the in-project human + embedded agent.
PACKAGE_REFERENCE_DIR = SRC / "scistudio" / "_user_guide" / "api-reference"
SITE_DIR = REPO_ROOT / "build" / "mkdocs-site"  # gitignored (build/)
MKDOCS_CONFIG = REPO_ROOT / "mkdocs.yml"

_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/docs/build_reference.py (ADR-052 §7). "
    "Do not hand-edit; regenerate from docstrings + stability decorators. -->\n"
)


def _core_version() -> str:
    """Best-effort core version string for the single-version stamp (ADR-052 §7)."""
    try:
        import scistudio

        version = getattr(scistudio, "__version__", None)
        if version:
            return str(version)
    except Exception:  # pragma: no cover - defensive
        pass
    try:
        from scistudio._version import BASE_VERSION, CHANNEL

        return f"{BASE_VERSION} ({CHANNEL})"
    except Exception:  # pragma: no cover - defensive
        return "unknown"


def _symbol_kind(obj: object) -> str:
    """Classify a public symbol for its heading label."""
    if inspect.isclass(obj):
        if isinstance(obj, enum.EnumType):
            return "enum"
        if issubclass(obj, BaseException):
            return "exception"
        if getattr(obj, "_is_protocol", False):
            return "protocol"
        return "class"
    if inspect.isroutine(obj):
        return "function"
    if isinstance(obj, (types.GenericAlias, types.UnionType)) or "Alias" in type(obj).__name__:
        return "type-alias"
    return "constant"


def _badge(obj: object) -> str:
    """Render the tier / Since badge for a symbol from ``get_stability``.

    Reads the single source of truth. A symbol whose tier cannot be machine-read
    (a bare ``str`` constant or a ``list[...]`` / ``collections.abc.Callable``
    generic-alias has no writable ``__dict__``) renders as *unmarked*; its tier
    is recorded in the module source and the spec (ADR-052 §8.1).
    """
    info = get_stability(obj)
    if info is None:
        return "> _Stability: unmarked — see the module docstring / ADR-052 for this constant or type-alias._"
    since = f" · **Since:** `{info.since}`" if info.since else ""
    return f"> **Stability:** `{info.tier}`{since}"


def _internal_member_filters(cls: type) -> list[str]:
    """``mkdocstrings`` filters excluding non-underscore ``internal``-tier members.

    Class members are otherwise filtered only by the default ``!^_`` rule, so an
    ``internal``-tier method with a public-looking name (e.g.
    ``PreviewDataAccess.png_data_uri``) would leak into the reference; this
    excludes it (ADR-052 §7 — ``internal`` symbols are excluded).
    """
    filters: list[str] = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        info = get_stability(value)
        if info is not None and info.tier == "internal":
            filters.append(f'"!^{name}$"')
    return filters


def _directive(path: str, *, is_class: bool, extra_filters: list[str]) -> str:
    filters = ['"!^_"', *extra_filters]
    lines = [
        f"::: {path}",
        "    options:",
        "      show_root_heading: false",
        "      show_root_toc_entry: false",
        "      show_source: false",
        "      heading_level: 4",
        "      members_order: source",
        f"      filters: [{', '.join(filters)}]",
    ]
    if not is_class:
        lines.append("      show_labels: false")
    return "\n".join(lines)


def _render_root_page(root: str) -> tuple[str, int, int]:
    """Render one root's reference page. Returns (markdown, public_count, marked_count)."""
    module = importlib.import_module(root)
    public = sorted(getattr(module, "__all__", []))
    marked = 0

    body = [
        _GENERATED_BANNER,
        f"# `{root}`\n",
        f"Canonical import root: `from {root} import ...`\n",
        "Public surface — every symbol below is declared in this module's "
        f"`__all__` ({len(public)} symbols). Stability tier and `Since` are read "
        "from the `scistudio.stability` decorators (ADR-052 §5/§7).\n",
    ]

    for name in public:
        obj = getattr(module, name)
        kind = _symbol_kind(obj)
        if get_stability(obj) is not None:
            marked += 1
        is_class = inspect.isclass(obj)
        extra_filters = _internal_member_filters(obj) if is_class else []
        body.append(f"## `{name}` — _{kind}_\n")
        body.append(_badge(obj) + "\n")
        body.append(_directive(f"{root}.{name}", is_class=is_class, extra_filters=extra_filters) + "\n")

    return "\n".join(body) + "\n", len(public), marked


def _render_index(stats: list[tuple[str, int, int]]) -> str:
    version = _core_version()
    lines = [
        _GENERATED_BANNER,
        "# SciStudio API Reference\n",
        f"**Version:** `{version}` — single-version reference for this release "
        "(ADR-052 §7; multi-version hosting via `mike` is a tracked follow-up, "
        "#1817).\n",
        "This reference is **generated** from the public API's docstrings and "
        "the `scistudio.stability` decorators (ADR-052 §7). It contains only the "
        "public surface — the symbols declared in each canonical root's "
        "`__all__`; `internal` symbols are excluded. Do not hand-edit; "
        "regenerate with `scripts/docs/build_reference.py`.\n",
        "## Stability tiers\n",
        "- **`stable`** — supported; no incompatible change within a major "
        "version without deprecation first.\n"
        "- **`provisional`** — usable but still settling; may change in a minor "
        "release with a changelog note.\n"
        "- **`internal`** — excluded from this reference (no promise).\n",
        "A handful of public constants and type-aliases (a bare `str`, a "
        "`list[...]` or `collections.abc.Callable` alias) cannot carry a runtime "
        "stability marker and render as *unmarked*; their tier is recorded in "
        "the module source and the spec (ADR-052 §8.1).\n",
        "## Canonical public roots\n",
    ]
    for root, public_count, marked in stats:
        page = f"{root}.md"
        lines.append(f"- [`{root}`]({page}) — {public_count} public symbols ({marked} stability-marked)")
    lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Self-contained renderer (#1850): real signatures + docstrings inlined, so the
# reference is readable without an mkdocs build and can be provisioned as-is.
# --------------------------------------------------------------------------


def _sc_badge(obj: object) -> str:
    info = get_stability(obj)
    if info is None:
        return "_unmarked — see the module source / ADR-052_"
    since = f" · Since `{info.since}`" if info.since else ""
    return f"`{info.tier}`{since}"


def _sc_signature(obj: object) -> str | None:
    """Best-effort signature string; ``None`` when uninspectable."""
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return None


def _sc_firstline(doc: str | None) -> str:
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        if line.strip():
            return _strip_sphinx_roles(line.strip())
    return ""


def _sc_public_members(cls: type) -> list[tuple[str, object]]:
    """Public, non-``internal`` members defined on ``cls`` itself (not inherited)."""
    members: list[tuple[str, object]] = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        info = get_stability(value)
        if info is not None and info.tier == "internal":
            continue
        if (
            inspect.isfunction(value)
            or inspect.ismethod(value)
            or isinstance(value, (property, staticmethod, classmethod))
        ):
            members.append((name, value))
    return members


def _sc_render_symbol(root: str, name: str, obj: object) -> str:
    kind = _symbol_kind(obj)
    out = [f"## `{name}` — _{kind}_", "", f"**Stability:** {_sc_badge(obj)}", ""]

    if inspect.isclass(obj):
        bases = [b.__name__ for b in obj.__bases__ if b is not object]
        header = f"class {name}({', '.join(bases)})" if bases else f"class {name}"
        init = obj.__dict__.get("__init__")
        init_sig = _sc_signature(obj) if init is not None else None
        code = header + (f"\n{name}{init_sig}" if init_sig else "")
        out += ["```python", code, "```", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc:
            out += [doc, ""]
        methods = _sc_public_members(obj)
        if methods:
            out += ["**Members**", ""]
            for mname, mval in methods:
                target = (
                    mval.fget
                    if isinstance(mval, property)
                    else (mval.__func__ if isinstance(mval, (staticmethod, classmethod)) else mval)
                )
                sig = _sc_signature(target) or ""
                summary = _sc_firstline(inspect.getdoc(target))
                tier = _sc_badge(target)
                line = f"- `{mname}{sig}` — {tier}"
                if summary:
                    line += f" — {summary}"
                out.append(line)
            out.append("")
    elif inspect.isroutine(obj):
        sig = _sc_signature(obj) or "(...)"
        out += ["```python", f"{name}{sig}", "```", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc:
            out += [doc, ""]
    else:
        out += [f"_{kind}_ — see the module source for the value.", ""]
        doc = _strip_sphinx_roles(inspect.getdoc(obj) or "")
        if doc and doc != inspect.getdoc(type(obj)):
            out += [doc, ""]
    return "\n".join(out)


def _sc_render_root_page(root: str) -> tuple[str, int]:
    module = importlib.import_module(root)
    public = sorted(getattr(module, "__all__", []))
    body = [
        _GENERATED_BANNER,
        f"# `{root}`\n",
        f"Canonical import root: `from {root} import ...`\n",
        f"Self-contained public-API reference — {len(public)} symbols from this "
        "module's `__all__`, with signatures and docstrings inlined (ADR-052 §7). "
        "Generated; do not hand-edit.\n",
    ]
    for name in public:
        body.append(_sc_render_symbol(root, name, getattr(module, name)))
    return "\n".join(body) + "\n", len(public)


def _sc_render_index(stats: list[tuple[str, int]]) -> str:
    version = _core_version()
    lines = [
        _GENERATED_BANNER,
        "# SciStudio API reference\n",
        f"**Version:** `{version}` (single-version for this release, ADR-052 §7).\n",
        "The public API you may rely on, generated from the code's docstrings and "
        "`scistudio.stability` decorators. Only the public surface (each canonical "
        "root's `__all__`) appears; `internal` symbols are excluded. Import from the "
        "canonical root shown on each page, never a deeper module path.\n",
        "## Stability\n",
        "- `stable` — supported; no incompatible change within a major version "
        "without deprecation.\n"
        "- `provisional` — usable, may change in a minor release.\n"
        "- `internal` — excluded from this reference.\n",
        "## Canonical roots\n",
    ]
    for root, count in stats:
        lines.append(f"- [`{root}`]({root}.md) — {count} symbols")
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_selfcontained() -> list[tuple[str, int]]:
    """Generate the self-contained reference under ``PACKAGE_REFERENCE_DIR`` (#1850)."""
    PACKAGE_REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    stats: list[tuple[str, int]] = []
    for root in CANONICAL_ROOTS:
        page, count = _sc_render_root_page(root)
        (PACKAGE_REFERENCE_DIR / f"{root}.md").write_text(page, encoding="utf-8")
        stats.append((root, count))
        print(f"  [self-contained] wrote {root}.md  ({count} symbols)")
    (PACKAGE_REFERENCE_DIR / "index.md").write_text(_sc_render_index(stats), encoding="utf-8")
    print(f"  [self-contained] wrote index.md  (version {_core_version()})")
    return stats


def generate() -> list[tuple[str, int, int]]:
    """Generate index + per-root pages under ``docs/user/reference/``."""
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    stats: list[tuple[str, int, int]] = []
    for root in CANONICAL_ROOTS:
        page, public_count, marked = _render_root_page(root)
        (REFERENCE_DIR / f"{root}.md").write_text(page, encoding="utf-8")
        stats.append((root, public_count, marked))
        print(f"  wrote {root}.md  ({public_count} public, {marked} marked)")
    (REFERENCE_DIR / "index.md").write_text(_render_index(stats), encoding="utf-8")
    print(f"  wrote index.md  (version {_core_version()})")
    return stats


def build_strict() -> int:
    """Run ``mkdocs build --strict`` into the gitignored build dir."""
    cmd = [
        sys.executable,
        "-m",
        "mkdocs",
        "build",
        "--strict",
        "--config-file",
        str(MKDOCS_CONFIG),
        "--site-dir",
        str(SITE_DIR),
    ]
    print(f"  $ {' '.join(cmd)}")
    return subprocess.call(cmd, cwd=str(REPO_ROOT))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Generate the reference Markdown but skip the mkdocs --strict build.",
    )
    args = parser.parse_args(argv)

    print("Generating ADR-052 §7 public API reference ...")
    generate()
    print("Generating self-contained reference (#1850) ...")
    generate_selfcontained()
    if args.generate_only:
        print("Generated (skipped mkdocs build).")
        return 0
    rc = build_strict()
    if rc == 0:
        print(f"mkdocs build --strict OK -> {SITE_DIR}")
    else:
        print(f"mkdocs build --strict FAILED (exit {rc})", file=sys.stderr)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
