"""The generated workflow YAML reference is fresh and refuses to drift from the workflow models."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest
import yaml
from pydantic import BaseModel, Field, field_validator

from scistudio.workflow.schema import WorkflowFileModel

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "src" / "scistudio" / "_user_guide" / "api-reference"


def _load_generator() -> ModuleType:
    path = ROOT / "scripts" / "docs" / "build_workflow_reference.py"
    spec = importlib.util.spec_from_file_location("build_workflow_reference", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("build_workflow_reference", module)
    spec.loader.exec_module(module)
    return module


gen = _load_generator()


def test_committed_workflow_reference_matches_a_fresh_render() -> None:
    committed = (REFERENCE / gen.PAGE).read_text(encoding="utf-8")
    assert committed == gen.render_page(), (
        f"{gen.PAGE} is stale; regenerate with PYTHONPATH=src python scripts/docs/build_workflow_reference.py"
    )


def test_reference_index_links_the_workflow_page() -> None:
    index = (REFERENCE / "index.md").read_text(encoding="utf-8")
    for line in gen.index_lines():
        assert line.strip() in index
    assert f"]({gen.PAGE})" in index


def test_page_carries_banner_and_stability() -> None:
    page = gen.render_page()
    assert page.startswith("<!-- GENERATED by scripts/docs/build_workflow_reference.py.")
    assert "**Stability:** `provisional`" in page


def test_every_model_and_key_is_rendered() -> None:
    page = gen.render_page()
    schema = WorkflowFileModel.model_json_schema()
    definitions = {schema["title"]: schema, **schema["$defs"]}
    assert {name for name, _ in gen.sections()} == set(definitions)
    for definition in definitions.values():
        for key in definition["properties"]:
            assert f"| `{key}` |" in page


def test_sections_follow_the_file_nesting() -> None:
    paths = dict(gen.sections())
    assert paths["WorkflowFileModel"] == ""
    assert paths["WorkflowModel"] == "`workflow`"
    assert paths["NodeModel"] == "`workflow.nodes[]`"
    assert paths["EdgeModel"] == "`workflow.edges[]`"
    assert paths["ExposedPortModel"] == "`workflow.exposed_ports.inputs[]` / `workflow.exposed_ports.outputs[]`"


def test_every_validation_check_is_rendered() -> None:
    page = gen.render_page()
    for number in range(1, 13):
        assert f"\n{number}. **" in page
    assert "Validation runs in one of two modes." in page


def test_examples_load_as_workflow_files_and_round_trip() -> None:
    page = gen.render_page()
    for path, definition in gen.example_files():
        text = gen.dump_yaml_str(definition)
        assert text.rstrip() in page, path
        loaded = WorkflowFileModel.model_validate(yaml.safe_load(text))
        assert loaded.workflow.to_definition() == definition
        assert Path(path).stem == definition.id


def test_examples_validate_against_the_builtin_blocks(tmp_path: Path) -> None:
    from scistudio.blocks.registry import BlockRegistry
    from scistudio.workflow.flatten import flatten_subworkflows
    from scistudio.workflow.serializer import load_yaml, save_yaml
    from scistudio.workflow.validator import validate_workflow

    for path, definition in gen.example_files():
        target = tmp_path / path
        target.parent.mkdir(parents=True, exist_ok=True)
        save_yaml(definition, target)

    registry = BlockRegistry()
    registry.scan()
    parent_path = tmp_path / gen.example_files()[0][0]
    flat = flatten_subworkflows(load_yaml(parent_path), tmp_path, registry=registry, self_path=parent_path)
    diagnostics = validate_workflow(flat, registry=registry, project_dir=tmp_path)
    assert diagnostics == []


# --------------------------------------------------------------------------
# Drift guards
# --------------------------------------------------------------------------


def test_a_key_without_a_description_is_refused(monkeypatch: pytest.MonkeyPatch) -> None:
    class Undocumented(BaseModel):
        """A model with an undocumented key."""

        name: str

    class File(BaseModel):
        """A file."""

        body: Undocumented = Field(description="The body.")

    monkeypatch.setattr(gen, "ROOT_MODEL", File)
    monkeypatch.setattr(gen, "_models_by_name", lambda: {"File": File, "Undocumented": Undocumented})
    with pytest.raises(gen.WorkflowReferenceError, match=r"Undocumented\.name has no description"):
        gen.render_page()


def test_a_model_without_its_own_docstring_is_refused(monkeypatch: pytest.MonkeyPatch) -> None:
    class Bare(BaseModel):
        name: str = Field(description="A name.")

    monkeypatch.setattr(gen, "ROOT_MODEL", Bare)
    monkeypatch.setattr(gen, "_models_by_name", lambda: {"Bare": Bare})
    with pytest.raises(gen.WorkflowReferenceError, match="has no docstring of its own"):
        gen.render_page()


def test_a_validator_without_a_docstring_is_refused(monkeypatch: pytest.MonkeyPatch) -> None:
    class Checked(BaseModel):
        """A model with an undocumented rule."""

        name: str = Field(description="A name.")

        @field_validator("name")
        @classmethod
        def no_spaces(cls, v: str) -> str:
            return v

    monkeypatch.setattr(gen, "ROOT_MODEL", Checked)
    monkeypatch.setattr(gen, "_models_by_name", lambda: {"Checked": Checked})
    with pytest.raises(gen.WorkflowReferenceError, match="validator no_spaces has no docstring"):
        gen.render_page()
