"""The generated panel API reference is fresh and refuses to drift from the panel sources."""

from __future__ import annotations

import importlib.util
import re
import shutil
import sys
from pathlib import Path
from types import ModuleType

import pytest

from scistudio.panels.reads import READ_OPERATIONS

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "src" / "scistudio" / "_user_guide" / "api-reference"


def _load_generator() -> ModuleType:
    path = ROOT / "scripts" / "docs" / "build_panel_reference.py"
    spec = importlib.util.spec_from_file_location("build_panel_reference", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("build_panel_reference", module)
    spec.loader.exec_module(module)
    return module


gen = _load_generator()


def test_committed_panel_reference_matches_a_fresh_render() -> None:
    for name, text in gen.render_pages().items():
        committed = (REFERENCE / name).read_text(encoding="utf-8")
        assert committed == text, (
            f"{name} is stale; regenerate with PYTHONPATH=src python scripts/docs/build_panel_reference.py"
        )


def test_reference_index_links_every_panel_page() -> None:
    index = (REFERENCE / "index.md").read_text(encoding="utf-8")
    for line in gen.index_section():
        assert line.strip() in index
    for page in gen.PAGES:
        assert f"]({page})" in index


def test_pages_carry_stability_and_api_version() -> None:
    from scistudio.panels.descriptor import PANEL_API_VERSION

    for text in gen.render_pages().values():
        assert "Stability:** `provisional`" in text
        assert f"Panel API version:** `{PANEL_API_VERSION}`" in text
        assert text.startswith("<!-- GENERATED by scripts/docs/build_panel_reference.py.")


def test_read_operations_match_the_host_bridge_allowlist() -> None:
    bridge = (ROOT / "frontend" / "src" / "panels" / "bridge.ts").read_text(encoding="utf-8")
    block = re.search(r"const READ_OPS = new Set\(\[(.*?)\]\)", bridge, re.S)
    assert block is not None
    assert set(re.findall(r'"([\w.]+)"', block.group(1))) == set(READ_OPERATIONS)


def test_every_descriptor_field_and_read_operation_is_rendered() -> None:
    from scistudio.panels.descriptor import DESCRIPTOR_FIELDS

    pages = gen.render_pages()
    for field in DESCRIPTOR_FIELDS:
        assert f"| `{field.key}` |" in pages[gen.DESCRIPTOR_PAGE]
    for op in READ_OPERATIONS:
        assert f"| `{op}` |" in pages[gen.SDK_PAGE]


# --------------------------------------------------------------------------
# Parser and drift guards
# --------------------------------------------------------------------------


def test_signature_reads_destructured_props_defaults_and_rest() -> None:
    signature = gen.parse_signature('{ class: cls, query = { page: 1, size: "a,b" }, onChange = () => {}, ...rest }')
    assert signature.props == {"class": None, "query": '{ page: 1, size: "a,b" }', "onChange": "() => {}"}
    assert signature.has_rest
    assert gen.parse_signature("props").props is None


def test_param_type_may_contain_braces() -> None:
    (block,) = gen.parse_blocks(
        "/**\n * Text.\n *\n * @param {Array<string | {value, label}>} [props.options] Choices.\n */", where="t"
    )
    (param,) = block.params
    assert (param.name, param.type, param.optional, param.description) == (
        "props.options",
        "Array<string | {value, label}>",
        True,
        "Choices.",
    )
    assert block.description == "Text."


def _write_module(tmp_path: Path, body: str) -> Path:
    path = tmp_path / "module.js"
    path.write_text(body, encoding="utf-8")
    return path


def test_undocumented_export_is_refused(tmp_path: Path) -> None:
    (component,) = gen._exported_components(_write_module(tmp_path, "export function Bare({ a }) {}\n")).values()
    with pytest.raises(gen.PanelReferenceError, match="without a JSDoc"):
        gen._check_component(component)


def test_prop_drift_is_refused(tmp_path: Path) -> None:
    source = "/**\n * Shows a.\n *\n * @param {string} [props.b] Not taken.\n */\nexport function View({ a }) {}\n"
    (component,) = gen._exported_components(_write_module(tmp_path, source)).values()
    with pytest.raises(gen.PanelReferenceError, match=r"undocumented \['a'\].*not taken \['b'\]"):
        gen._check_component(component)


def _sdk_copy(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    sdk = tmp_path / "sdk"
    shutil.copytree(gen.SDK_DIR, sdk)
    monkeypatch.setattr(gen, "SDK_DIR", sdk)
    return sdk / "scistudio-panel.js"


def test_undocumented_sdk_member_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    script = _sdk_copy(tmp_path, monkeypatch)
    source = script.read_text(encoding="utf-8")
    script.write_text(source.replace("  window.scistudio = api;", "  api.extra = 1;\n  window.scistudio = api;"))
    with pytest.raises(gen.PanelReferenceError, match=r"undocumented members \['extra'\]"):
        gen.render_sdk_page()


def test_undocumented_sdk_error_code_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    script = _sdk_copy(tmp_path, monkeypatch)
    source = script.read_text(encoding="utf-8")
    script.write_text(source.replace('failure("timeout"', 'failure("too_slow"'))
    with pytest.raises(gen.PanelReferenceError, match="too_slow"):
        gen.render_sdk_page()


def test_sample_key_drift_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    script = _sdk_copy(tmp_path, monkeypatch)
    source = script.read_text(encoding="utf-8")
    script.write_text(source.replace("viewState: loaded.viewState,", "viewState: loaded.state,"))
    with pytest.raises(gen.PanelReferenceError, match=r"undocumented \['state'\]"):
        gen.render_descriptor_page()


def test_generate_writes_every_page(tmp_path: Path) -> None:
    written = gen.generate(tmp_path)
    assert sorted(written) == sorted(gen.PAGES)
    for name in written:
        assert (tmp_path / name).read_text(encoding="utf-8").endswith("\n")
